import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/auth";
import { createArticle, listAllArticles } from "@/lib/store";
import type { ArticleInput, ArticleSeo, CategoryId, RegionId } from "@/lib/types";

export async function GET() {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const articles = await listAllArticles();
  return NextResponse.json({ articles });
}

export async function POST(req: Request) {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  try {
    const body = (await req.json()) as Partial<ArticleInput> & {
      seo?: ArticleSeo;
    };
    if (!body.title?.trim()) {
      return NextResponse.json({ error: "Title is required" }, { status: 400 });
    }
    let content: string[];
    if (Array.isArray(body.content)) {
      content = body.content;
    } else {
      const raw = String(body.content || body.dek || body.title);
      if (raw.includes("<")) {
        const { htmlToParagraphs } = await import("@/lib/editor-content");
        content = htmlToParagraphs(raw);
      } else {
        content = raw
          .split(/\n+/)
          .map((p) => p.trim())
          .filter(Boolean);
      }
    }

    const article = await createArticle({
      title: body.title.trim(),
      dek: body.dek?.trim() || body.title.trim(),
      content,
      category: (body.category as CategoryId) || "politics",
      region: (body.region as RegionId) || "global",
      city: body.city || "Global",
      country: body.country || "World",
      lat: Number(body.lat ?? 20),
      lng: Number(body.lng ?? 0),
      author: body.author || "World Grid Desk",
      image:
        body.image ||
        "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1600&q=80",
      imageAlt: body.imageAlt || body.title,
      featured: Boolean(body.featured),
      breaking: Boolean(body.breaking),
      tags: Array.isArray(body.tags)
        ? body.tags
        : String(body.tags || "")
            .split(",")
            .map((t) => t.trim())
            .filter(Boolean),
      status: body.status === "draft" ? "draft" : "published",
      autoGenerated: Boolean(body.autoGenerated),
      aiGenerated: Boolean(body.aiGenerated),
      aiProvider: body.aiProvider,
      source: body.source,
      sourceUrl: body.sourceUrl,
      publishedAt: body.publishedAt,
      slug: body.slug,
      seo: body.seo,
    });
    return NextResponse.json({ article }, { status: 201 });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Create failed" },
      { status: 500 },
    );
  }
}
