import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/auth";
import { createArticle, listAllArticles } from "@/lib/store";
import { assertSameOrigin } from "@/lib/rate-limit";
import {
  sanitizeContentBlocks,
  sanitizeHttpUrl,
  sanitizeLocalUploadPath,
} from "@/lib/sanitize";
import {
  articleCreateSchema,
  parseTags,
} from "@/lib/validation";
import type { ArticleInput, CategoryId, RegionId } from "@/lib/types";

export async function GET() {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const articles = await listAllArticles();
  return NextResponse.json({ articles });
}

export async function POST(req: Request) {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (process.env.NODE_ENV === "production" && !assertSameOrigin(req)) {
    return NextResponse.json({ error: "Invalid origin" }, { status: 403 });
  }
  try {
    const raw = await req.json();
    const parsed = articleCreateSchema.safeParse(raw);
    if (!parsed.success) {
      return NextResponse.json(
        {
          error: "Validation failed",
          details: parsed.error.flatten().fieldErrors,
        },
        { status: 400 },
      );
    }
    const body = parsed.data;

    let content: string[];
    if (Array.isArray(body.content)) {
      content = sanitizeContentBlocks(body.content);
    } else {
      const rawContent = String(body.content || body.dek || body.title || "");
      if (rawContent.includes("<")) {
        const { htmlToParagraphs } = await import("@/lib/editor-content");
        content = sanitizeContentBlocks(htmlToParagraphs(rawContent));
      } else {
        content = sanitizeContentBlocks(
          rawContent
            .split(/\n+/)
            .map((p) => p.trim())
            .filter(Boolean),
        );
      }
    }

    if (!content.length) {
      content = sanitizeContentBlocks([body.dek || body.title]);
    }

    const imageUrl =
      sanitizeHttpUrl(body.image) ||
      sanitizeLocalUploadPath(body.image) ||
      "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1600&q=80";

    const input: ArticleInput = {
      title: body.title.trim(),
      dek: (body.dek || body.title).trim(),
      content,
      category: (body.category as CategoryId) || "politics",
      region: (body.region as RegionId) || "global",
      city: body.city || "Global",
      country: body.country || "World",
      lat: body.lat ?? 20,
      lng: body.lng ?? 0,
      author: body.author || "World Grid Desk",
      image: imageUrl,
      imageAlt: body.imageAlt || body.title,
      featured: Boolean(body.featured),
      breaking: Boolean(body.breaking),
      tags: parseTags(body.tags),
      status: body.status === "draft" ? "draft" : "published",
      autoGenerated: Boolean(body.autoGenerated),
      aiGenerated: Boolean(body.aiGenerated),
      aiProvider: body.aiProvider,
      source: body.source,
      sourceUrl: sanitizeHttpUrl(body.sourceUrl) || undefined,
      publishedAt: body.publishedAt,
      slug: body.slug,
      seo: body.seo
        ? {
            ...body.seo,
            canonicalUrl: sanitizeHttpUrl(body.seo.canonicalUrl) || undefined,
            ogImage:
              sanitizeHttpUrl(body.seo.ogImage) ||
              sanitizeLocalUploadPath(body.seo.ogImage) ||
              undefined,
          }
        : undefined,
    };

    const article = await createArticle(input);
    return NextResponse.json({ article }, { status: 201 });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Create failed" },
      { status: 500 },
    );
  }
}
