import type { RegionId } from "./types";

export type GeoPlace = {
  /** Lowercase aliases / substrings to match in article text. Longer keys win. */
  keys: string[];
  city: string;
  country: string;
  region: RegionId;
  lat: number;
  lng: number;
};

export type InferredGeo = {
  region: RegionId;
  city: string;
  country: string;
  lat: number;
  lng: number;
};

/**
 * Major cities + country/region fallbacks for map pins.
 * City entries use specific aliases; country entries catch broader mentions.
 */
export const GEO_PLACES: GeoPlace[] = [
  // ── Europe (cities) ──────────────────────────────────────────────
  {
    keys: ["london", "westminster", "downing street"],
    city: "London",
    country: "United Kingdom",
    region: "europe",
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    keys: ["paris", "élysée", "elysee"],
    city: "Paris",
    country: "France",
    region: "europe",
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    keys: ["berlin", "bundestag"],
    city: "Berlin",
    country: "Germany",
    region: "europe",
    lat: 52.52,
    lng: 13.405,
  },
  {
    keys: ["moscow", "kremlin"],
    city: "Moscow",
    country: "Russia",
    region: "europe",
    lat: 55.7558,
    lng: 37.6173,
  },
  {
    keys: ["kyiv", "kiev"],
    city: "Kyiv",
    country: "Ukraine",
    region: "europe",
    lat: 50.4501,
    lng: 30.5234,
  },
  {
    keys: ["kharkiv", "kharkov"],
    city: "Kharkiv",
    country: "Ukraine",
    region: "europe",
    lat: 49.9935,
    lng: 36.2304,
  },
  {
    keys: ["odesa", "odessa"],
    city: "Odesa",
    country: "Ukraine",
    region: "europe",
    lat: 46.4825,
    lng: 30.7233,
  },
  {
    keys: ["lviv", "lvov"],
    city: "Lviv",
    country: "Ukraine",
    region: "europe",
    lat: 49.8397,
    lng: 24.0297,
  },
  {
    keys: ["donetsk"],
    city: "Donetsk",
    country: "Ukraine",
    region: "europe",
    lat: 48.0159,
    lng: 37.8028,
  },
  {
    keys: ["mariupol"],
    city: "Mariupol",
    country: "Ukraine",
    region: "europe",
    lat: 47.0971,
    lng: 37.5434,
  },
  {
    keys: ["zaporizhzhia", "zaporizhia", "zaporozhye"],
    city: "Zaporizhzhia",
    country: "Ukraine",
    region: "europe",
    lat: 47.8388,
    lng: 35.1396,
  },
  {
    keys: ["saint petersburg", "st. petersburg", "st petersburg", "petersburg"],
    city: "Saint Petersburg",
    country: "Russia",
    region: "europe",
    lat: 59.9343,
    lng: 30.3351,
  },
  {
    keys: ["warsaw"],
    city: "Warsaw",
    country: "Poland",
    region: "europe",
    lat: 52.2297,
    lng: 21.0122,
  },
  {
    keys: ["krakow", "cracow", "kraków"],
    city: "Kraków",
    country: "Poland",
    region: "europe",
    lat: 50.0647,
    lng: 19.945,
  },
  {
    keys: ["gdansk", "gdańsk"],
    city: "Gdańsk",
    country: "Poland",
    region: "europe",
    lat: 54.352,
    lng: 18.6466,
  },
  {
    keys: ["rome", "vatican"],
    city: "Rome",
    country: "Italy",
    region: "europe",
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    keys: ["milan", "milano"],
    city: "Milan",
    country: "Italy",
    region: "europe",
    lat: 45.4642,
    lng: 9.19,
  },
  {
    keys: ["naples", "napoli"],
    city: "Naples",
    country: "Italy",
    region: "europe",
    lat: 40.8518,
    lng: 14.2681,
  },
  {
    keys: ["madrid"],
    city: "Madrid",
    country: "Spain",
    region: "europe",
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    keys: ["barcelona"],
    city: "Barcelona",
    country: "Spain",
    region: "europe",
    lat: 41.3874,
    lng: 2.1686,
  },
  {
    keys: ["ceuta"],
    city: "Ceuta",
    country: "Spain",
    region: "europe",
    lat: 35.8894,
    lng: -5.3213,
  },
  {
    keys: ["melilla"],
    city: "Melilla",
    country: "Spain",
    region: "europe",
    lat: 35.2923,
    lng: -2.9381,
  },
  {
    keys: ["valencia"],
    city: "Valencia",
    country: "Spain",
    region: "europe",
    lat: 39.4699,
    lng: -0.3763,
  },
  {
    keys: ["brussels", "eu commission", "european commission"],
    city: "Brussels",
    country: "Belgium",
    region: "europe",
    lat: 50.8503,
    lng: 4.3517,
  },
  {
    keys: ["amsterdam"],
    city: "Amsterdam",
    country: "Netherlands",
    region: "europe",
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    keys: ["the hague", "hague", "den haag"],
    city: "The Hague",
    country: "Netherlands",
    region: "europe",
    lat: 52.0705,
    lng: 4.3007,
  },
  {
    keys: ["rotterdam"],
    city: "Rotterdam",
    country: "Netherlands",
    region: "europe",
    lat: 51.9244,
    lng: 4.4777,
  },
  {
    keys: ["vienna"],
    city: "Vienna",
    country: "Austria",
    region: "europe",
    lat: 48.2082,
    lng: 16.3738,
  },
  {
    keys: ["stockholm"],
    city: "Stockholm",
    country: "Sweden",
    region: "europe",
    lat: 59.3293,
    lng: 18.0686,
  },
  {
    keys: ["oslo"],
    city: "Oslo",
    country: "Norway",
    region: "europe",
    lat: 59.9139,
    lng: 10.7522,
  },
  {
    keys: ["copenhagen"],
    city: "Copenhagen",
    country: "Denmark",
    region: "europe",
    lat: 55.6761,
    lng: 12.5683,
  },
  {
    keys: ["athens"],
    city: "Athens",
    country: "Greece",
    region: "europe",
    lat: 37.9838,
    lng: 23.7275,
  },
  {
    keys: ["lisbon"],
    city: "Lisbon",
    country: "Portugal",
    region: "europe",
    lat: 38.7223,
    lng: -9.1393,
  },
  {
    keys: ["porto"],
    city: "Porto",
    country: "Portugal",
    region: "europe",
    lat: 41.1579,
    lng: -8.6291,
  },
  {
    keys: ["prague"],
    city: "Prague",
    country: "Czech Republic",
    region: "europe",
    lat: 50.0755,
    lng: 14.4378,
  },
  {
    keys: ["budapest"],
    city: "Budapest",
    country: "Hungary",
    region: "europe",
    lat: 47.4979,
    lng: 19.0402,
  },
  {
    keys: ["bucharest"],
    city: "Bucharest",
    country: "Romania",
    region: "europe",
    lat: 44.4268,
    lng: 26.1025,
  },
  {
    keys: ["sofia"],
    city: "Sofia",
    country: "Bulgaria",
    region: "europe",
    lat: 42.6977,
    lng: 23.3219,
  },
  {
    keys: ["belgrade"],
    city: "Belgrade",
    country: "Serbia",
    region: "europe",
    lat: 44.7866,
    lng: 20.4489,
  },
  {
    keys: ["zagreb"],
    city: "Zagreb",
    country: "Croatia",
    region: "europe",
    lat: 45.815,
    lng: 15.9819,
  },
  {
    keys: ["sarajevo"],
    city: "Sarajevo",
    country: "Bosnia and Herzegovina",
    region: "europe",
    lat: 43.8563,
    lng: 18.4131,
  },
  {
    keys: ["tirana"],
    city: "Tirana",
    country: "Albania",
    region: "europe",
    lat: 41.3275,
    lng: 19.8187,
  },
  {
    keys: ["skopje"],
    city: "Skopje",
    country: "North Macedonia",
    region: "europe",
    lat: 41.9973,
    lng: 21.428,
  },
  {
    keys: ["podgorica"],
    city: "Podgorica",
    country: "Montenegro",
    region: "europe",
    lat: 42.4304,
    lng: 19.2594,
  },
  {
    keys: ["pristina", "priština", "prishtina"],
    city: "Pristina",
    country: "Kosovo",
    region: "europe",
    lat: 42.6629,
    lng: 21.1655,
  },
  {
    keys: ["helsinki"],
    city: "Helsinki",
    country: "Finland",
    region: "europe",
    lat: 60.1699,
    lng: 24.9384,
  },
  {
    keys: ["tallinn"],
    city: "Tallinn",
    country: "Estonia",
    region: "europe",
    lat: 59.437,
    lng: 24.7536,
  },
  {
    keys: ["riga"],
    city: "Riga",
    country: "Latvia",
    region: "europe",
    lat: 56.9496,
    lng: 24.1052,
  },
  {
    keys: ["vilnius"],
    city: "Vilnius",
    country: "Lithuania",
    region: "europe",
    lat: 54.6872,
    lng: 25.2797,
  },
  {
    keys: ["dublin"],
    city: "Dublin",
    country: "Ireland",
    region: "europe",
    lat: 53.3498,
    lng: -6.2603,
  },
  {
    keys: ["edinburgh"],
    city: "Edinburgh",
    country: "United Kingdom",
    region: "europe",
    lat: 55.9533,
    lng: -3.1883,
  },
  {
    keys: ["glasgow"],
    city: "Glasgow",
    country: "United Kingdom",
    region: "europe",
    lat: 55.8642,
    lng: -4.2518,
  },
  {
    keys: ["manchester"],
    city: "Manchester",
    country: "United Kingdom",
    region: "europe",
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    keys: ["birmingham"],
    city: "Birmingham",
    country: "United Kingdom",
    region: "europe",
    lat: 52.4862,
    lng: -1.8904,
  },
  {
    keys: ["belfast"],
    city: "Belfast",
    country: "United Kingdom",
    region: "europe",
    lat: 54.5973,
    lng: -5.9301,
  },
  {
    keys: ["munich", "münchen", "munchen"],
    city: "Munich",
    country: "Germany",
    region: "europe",
    lat: 48.1351,
    lng: 11.582,
  },
  {
    keys: ["hamburg"],
    city: "Hamburg",
    country: "Germany",
    region: "europe",
    lat: 53.5511,
    lng: 9.9937,
  },
  {
    keys: ["frankfurt"],
    city: "Frankfurt",
    country: "Germany",
    region: "europe",
    lat: 50.1109,
    lng: 8.6821,
  },
  {
    keys: ["cologne", "köln", "koln"],
    city: "Cologne",
    country: "Germany",
    region: "europe",
    lat: 50.9375,
    lng: 6.9603,
  },
  {
    keys: ["lyon"],
    city: "Lyon",
    country: "France",
    region: "europe",
    lat: 45.764,
    lng: 4.8357,
  },
  {
    keys: ["marseille"],
    city: "Marseille",
    country: "France",
    region: "europe",
    lat: 43.2965,
    lng: 5.3698,
  },
  {
    keys: ["nice"],
    city: "Nice",
    country: "France",
    region: "europe",
    lat: 43.7102,
    lng: 7.262,
  },
  {
    keys: ["zurich", "zürich"],
    city: "Zurich",
    country: "Switzerland",
    region: "europe",
    lat: 47.3769,
    lng: 8.5417,
  },
  {
    keys: ["geneva"],
    city: "Geneva",
    country: "Switzerland",
    region: "europe",
    lat: 46.2044,
    lng: 6.1432,
  },
  {
    keys: ["bern", "berne"],
    city: "Bern",
    country: "Switzerland",
    region: "europe",
    lat: 46.948,
    lng: 7.4474,
  },
  {
    keys: ["minsk"],
    city: "Minsk",
    country: "Belarus",
    region: "europe",
    lat: 53.9006,
    lng: 27.559,
  },
  {
    keys: ["chișinău", "chisinau", "kishinev"],
    city: "Chișinău",
    country: "Moldova",
    region: "europe",
    lat: 47.0105,
    lng: 28.8638,
  },
  {
    keys: ["tbilisi"],
    city: "Tbilisi",
    country: "Georgia",
    region: "europe",
    lat: 41.7151,
    lng: 44.8271,
  },
  {
    keys: ["yerevan"],
    city: "Yerevan",
    country: "Armenia",
    region: "europe",
    lat: 40.1792,
    lng: 44.4991,
  },
  {
    keys: ["baku"],
    city: "Baku",
    country: "Azerbaijan",
    region: "europe",
    lat: 40.4093,
    lng: 49.8671,
  },
  {
    keys: ["reykjavik", "reykjavík"],
    city: "Reykjavik",
    country: "Iceland",
    region: "europe",
    lat: 64.1466,
    lng: -21.9426,
  },
  {
    keys: ["luxembourg"],
    city: "Luxembourg",
    country: "Luxembourg",
    region: "europe",
    lat: 49.6116,
    lng: 6.1319,
  },
  {
    keys: ["nicosia"],
    city: "Nicosia",
    country: "Cyprus",
    region: "europe",
    lat: 35.1856,
    lng: 33.3823,
  },
  {
    keys: ["valletta", "malta"],
    city: "Valletta",
    country: "Malta",
    region: "europe",
    lat: 35.8989,
    lng: 14.5146,
  },

  // ── Americas (cities) ────────────────────────────────────────────
  {
    keys: [
      "washington dc",
      "washington d.c.",
      "washington",
      "white house",
      "capitol hill",
      "pentagon",
    ],
    city: "Washington",
    country: "United States",
    region: "americas",
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    keys: ["new york", "nyc", "manhattan", "brooklyn"],
    city: "New York",
    country: "United States",
    region: "americas",
    lat: 40.7128,
    lng: -74.006,
  },
  {
    keys: ["los angeles", "l.a.", "hollywood"],
    city: "Los Angeles",
    country: "United States",
    region: "americas",
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    keys: ["san francisco", "silicon valley"],
    city: "San Francisco",
    country: "United States",
    region: "americas",
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    keys: ["chicago"],
    city: "Chicago",
    country: "United States",
    region: "americas",
    lat: 41.8781,
    lng: -87.6298,
  },
  {
    keys: ["miami"],
    city: "Miami",
    country: "United States",
    region: "americas",
    lat: 25.7617,
    lng: -80.1918,
  },
  {
    keys: ["boston"],
    city: "Boston",
    country: "United States",
    region: "americas",
    lat: 42.3601,
    lng: -71.0589,
  },
  {
    keys: ["houston"],
    city: "Houston",
    country: "United States",
    region: "americas",
    lat: 29.7604,
    lng: -95.3698,
  },
  {
    keys: ["dallas"],
    city: "Dallas",
    country: "United States",
    region: "americas",
    lat: 32.7767,
    lng: -96.797,
  },
  {
    keys: ["seattle"],
    city: "Seattle",
    country: "United States",
    region: "americas",
    lat: 47.6062,
    lng: -122.3321,
  },
  {
    keys: ["atlanta"],
    city: "Atlanta",
    country: "United States",
    region: "americas",
    lat: 33.749,
    lng: -84.388,
  },
  {
    keys: ["denver"],
    city: "Denver",
    country: "United States",
    region: "americas",
    lat: 39.7392,
    lng: -104.9903,
  },
  {
    keys: ["phoenix"],
    city: "Phoenix",
    country: "United States",
    region: "americas",
    lat: 33.4484,
    lng: -112.074,
  },
  {
    keys: ["detroit"],
    city: "Detroit",
    country: "United States",
    region: "americas",
    lat: 42.3314,
    lng: -83.0458,
  },
  {
    keys: ["philadelphia", "philly"],
    city: "Philadelphia",
    country: "United States",
    region: "americas",
    lat: 39.9526,
    lng: -75.1652,
  },
  {
    keys: ["mexico city", "ciudad de méxico", "ciudad de mexico"],
    city: "Mexico City",
    country: "Mexico",
    region: "americas",
    lat: 19.4326,
    lng: -99.1332,
  },
  {
    keys: ["guadalajara"],
    city: "Guadalajara",
    country: "Mexico",
    region: "americas",
    lat: 20.6597,
    lng: -103.3496,
  },
  {
    keys: ["monterrey"],
    city: "Monterrey",
    country: "Mexico",
    region: "americas",
    lat: 25.6866,
    lng: -100.3161,
  },
  {
    keys: ["tijuana"],
    city: "Tijuana",
    country: "Mexico",
    region: "americas",
    lat: 32.5149,
    lng: -117.0382,
  },
  {
    keys: ["são paulo", "sao paulo"],
    city: "São Paulo",
    country: "Brazil",
    region: "americas",
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    keys: ["rio de janeiro", "rio "],
    city: "Rio de Janeiro",
    country: "Brazil",
    region: "americas",
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    keys: ["brasília", "brasilia"],
    city: "Brasília",
    country: "Brazil",
    region: "americas",
    lat: -15.8267,
    lng: -47.9218,
  },
  {
    keys: ["buenos aires"],
    city: "Buenos Aires",
    country: "Argentina",
    region: "americas",
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    keys: ["toronto"],
    city: "Toronto",
    country: "Canada",
    region: "americas",
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    keys: ["ottawa"],
    city: "Ottawa",
    country: "Canada",
    region: "americas",
    lat: 45.4215,
    lng: -75.6972,
  },
  {
    keys: ["vancouver"],
    city: "Vancouver",
    country: "Canada",
    region: "americas",
    lat: 49.2827,
    lng: -123.1207,
  },
  {
    keys: ["montreal", "montréal"],
    city: "Montreal",
    country: "Canada",
    region: "americas",
    lat: 45.5017,
    lng: -73.5673,
  },
  {
    keys: ["calgary"],
    city: "Calgary",
    country: "Canada",
    region: "americas",
    lat: 51.0447,
    lng: -114.0719,
  },
  {
    keys: ["bogotá", "bogota"],
    city: "Bogotá",
    country: "Colombia",
    region: "americas",
    lat: 4.711,
    lng: -74.0721,
  },
  {
    keys: ["medellín", "medellin"],
    city: "Medellín",
    country: "Colombia",
    region: "americas",
    lat: 6.2476,
    lng: -75.5658,
  },
  {
    keys: ["lima"],
    city: "Lima",
    country: "Peru",
    region: "americas",
    lat: -12.0464,
    lng: -77.0428,
  },
  {
    keys: ["santiago"],
    city: "Santiago",
    country: "Chile",
    region: "americas",
    lat: -33.4489,
    lng: -70.6693,
  },
  {
    keys: ["havana", "la habana"],
    city: "Havana",
    country: "Cuba",
    region: "americas",
    lat: 23.1136,
    lng: -82.3666,
  },
  {
    keys: ["caracas"],
    city: "Caracas",
    country: "Venezuela",
    region: "americas",
    lat: 10.4806,
    lng: -66.9036,
  },
  {
    keys: ["quito"],
    city: "Quito",
    country: "Ecuador",
    region: "americas",
    lat: -0.1807,
    lng: -78.4678,
  },
  {
    keys: ["la paz"],
    city: "La Paz",
    country: "Bolivia",
    region: "americas",
    lat: -16.5,
    lng: -68.15,
  },
  {
    keys: ["asunción", "asuncion"],
    city: "Asunción",
    country: "Paraguay",
    region: "americas",
    lat: -25.2637,
    lng: -57.5759,
  },
  {
    keys: ["montevideo"],
    city: "Montevideo",
    country: "Uruguay",
    region: "americas",
    lat: -34.9011,
    lng: -56.1645,
  },
  {
    keys: ["panama city", "panamá"],
    city: "Panama City",
    country: "Panama",
    region: "americas",
    lat: 8.9824,
    lng: -79.5199,
  },
  {
    keys: ["san josé", "san jose, costa", "costa rica"],
    city: "San José",
    country: "Costa Rica",
    region: "americas",
    lat: 9.9281,
    lng: -84.0907,
  },
  {
    keys: ["guatemala city"],
    city: "Guatemala City",
    country: "Guatemala",
    region: "americas",
    lat: 14.6349,
    lng: -90.5069,
  },
  {
    keys: ["santo domingo"],
    city: "Santo Domingo",
    country: "Dominican Republic",
    region: "americas",
    lat: 18.4861,
    lng: -69.9312,
  },
  {
    keys: ["port-au-prince", "port au prince", "haiti"],
    city: "Port-au-Prince",
    country: "Haiti",
    region: "americas",
    lat: 18.5944,
    lng: -72.3074,
  },
  {
    keys: ["kingston", "jamaica"],
    city: "Kingston",
    country: "Jamaica",
    region: "americas",
    lat: 18.0179,
    lng: -76.8099,
  },
  {
    keys: ["san juan"],
    city: "San Juan",
    country: "Puerto Rico",
    region: "americas",
    lat: 18.4655,
    lng: -66.1057,
  },

  // ── Africa (cities) ──────────────────────────────────────────────
  {
    keys: ["cairo"],
    city: "Cairo",
    country: "Egypt",
    region: "africa",
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    keys: ["alexandria"],
    city: "Alexandria",
    country: "Egypt",
    region: "africa",
    lat: 31.2001,
    lng: 29.9187,
  },
  {
    keys: ["lagos"],
    city: "Lagos",
    country: "Nigeria",
    region: "africa",
    lat: 6.5244,
    lng: 3.3792,
  },
  {
    keys: ["abuja"],
    city: "Abuja",
    country: "Nigeria",
    region: "africa",
    lat: 9.0765,
    lng: 7.3986,
  },
  {
    keys: ["kano"],
    city: "Kano",
    country: "Nigeria",
    region: "africa",
    lat: 12.0022,
    lng: 8.592,
  },
  {
    keys: ["nairobi"],
    city: "Nairobi",
    country: "Kenya",
    region: "africa",
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    keys: ["mombasa"],
    city: "Mombasa",
    country: "Kenya",
    region: "africa",
    lat: -4.0435,
    lng: 39.6682,
  },
  {
    keys: ["johannesburg", "joburg"],
    city: "Johannesburg",
    country: "South Africa",
    region: "africa",
    lat: -26.2041,
    lng: 28.0473,
  },
  {
    keys: ["cape town"],
    city: "Cape Town",
    country: "South Africa",
    region: "africa",
    lat: -33.9249,
    lng: 18.4241,
  },
  {
    keys: ["pretoria"],
    city: "Pretoria",
    country: "South Africa",
    region: "africa",
    lat: -25.7479,
    lng: 28.2293,
  },
  {
    keys: ["durban"],
    city: "Durban",
    country: "South Africa",
    region: "africa",
    lat: -29.8587,
    lng: 31.0218,
  },
  {
    keys: ["addis ababa"],
    city: "Addis Ababa",
    country: "Ethiopia",
    region: "africa",
    lat: 9.032,
    lng: 38.7469,
  },
  {
    keys: ["accra"],
    city: "Accra",
    country: "Ghana",
    region: "africa",
    lat: 5.6037,
    lng: -0.187,
  },
  {
    keys: ["casablanca"],
    city: "Casablanca",
    country: "Morocco",
    region: "africa",
    lat: 33.5731,
    lng: -7.5898,
  },
  {
    keys: ["rabat"],
    city: "Rabat",
    country: "Morocco",
    region: "africa",
    lat: 34.0209,
    lng: -6.8416,
  },
  {
    keys: ["marrakech", "marrakesh"],
    city: "Marrakech",
    country: "Morocco",
    region: "africa",
    lat: 31.6295,
    lng: -7.9811,
  },
  {
    keys: ["tunis"],
    city: "Tunis",
    country: "Tunisia",
    region: "africa",
    lat: 36.8065,
    lng: 10.1815,
  },
  {
    keys: ["algiers"],
    city: "Algiers",
    country: "Algeria",
    region: "africa",
    lat: 36.7538,
    lng: 3.0588,
  },
  {
    keys: ["dakar"],
    city: "Dakar",
    country: "Senegal",
    region: "africa",
    lat: 14.7167,
    lng: -17.4677,
  },
  {
    keys: ["kinshasa"],
    city: "Kinshasa",
    country: "DR Congo",
    region: "africa",
    lat: -4.4419,
    lng: 15.2663,
  },
  {
    keys: ["goma"],
    city: "Goma",
    country: "DR Congo",
    region: "africa",
    lat: -1.6785,
    lng: 29.2228,
  },
  {
    keys: ["lubumbashi"],
    city: "Lubumbashi",
    country: "DR Congo",
    region: "africa",
    lat: -11.6876,
    lng: 27.5026,
  },
  {
    keys: ["khartoum"],
    city: "Khartoum",
    country: "Sudan",
    region: "africa",
    lat: 15.5007,
    lng: 32.5599,
  },
  {
    keys: ["darfur"],
    city: "El Fasher",
    country: "Sudan",
    region: "africa",
    lat: 13.6279,
    lng: 25.3496,
  },
  {
    keys: ["mogadishu"],
    city: "Mogadishu",
    country: "Somalia",
    region: "africa",
    lat: 2.0469,
    lng: 45.3182,
  },
  {
    keys: ["kampala"],
    city: "Kampala",
    country: "Uganda",
    region: "africa",
    lat: 0.3476,
    lng: 32.5825,
  },
  {
    keys: ["kigali"],
    city: "Kigali",
    country: "Rwanda",
    region: "africa",
    lat: -1.9441,
    lng: 30.0619,
  },
  {
    keys: ["dar es salaam", "dodoma"],
    city: "Dar es Salaam",
    country: "Tanzania",
    region: "africa",
    lat: -6.7924,
    lng: 39.2083,
  },
  {
    keys: ["lusaka"],
    city: "Lusaka",
    country: "Zambia",
    region: "africa",
    lat: -15.3875,
    lng: 28.3228,
  },
  {
    keys: ["harare"],
    city: "Harare",
    country: "Zimbabwe",
    region: "africa",
    lat: -17.8252,
    lng: 31.0335,
  },
  {
    keys: ["maputo"],
    city: "Maputo",
    country: "Mozambique",
    region: "africa",
    lat: -25.9692,
    lng: 32.5732,
  },
  {
    keys: ["luanda"],
    city: "Luanda",
    country: "Angola",
    region: "africa",
    lat: -8.839,
    lng: 13.2894,
  },
  {
    keys: ["abidjan", "yamoussoukro"],
    city: "Abidjan",
    country: "Ivory Coast",
    region: "africa",
    lat: 5.36,
    lng: -4.0083,
  },
  {
    keys: ["bamako"],
    city: "Bamako",
    country: "Mali",
    region: "africa",
    lat: 12.6392,
    lng: -8.0029,
  },
  {
    keys: ["ouagadougou"],
    city: "Ouagadougou",
    country: "Burkina Faso",
    region: "africa",
    lat: 12.3714,
    lng: -1.5197,
  },
  {
    keys: ["niamey"],
    city: "Niamey",
    country: "Niger",
    region: "africa",
    lat: 13.5116,
    lng: 2.1254,
  },
  {
    keys: ["ndjamena", "n'djamena"],
    city: "N'Djamena",
    country: "Chad",
    region: "africa",
    lat: 12.1348,
    lng: 15.0557,
  },
  {
    keys: ["tripoli"],
    city: "Tripoli",
    country: "Libya",
    region: "africa",
    lat: 32.8872,
    lng: 13.1913,
  },
  {
    keys: ["benghazi"],
    city: "Benghazi",
    country: "Libya",
    region: "africa",
    lat: 32.1167,
    lng: 20.0667,
  },
  {
    keys: ["gaborone"],
    city: "Gaborone",
    country: "Botswana",
    region: "africa",
    lat: -24.6282,
    lng: 25.9231,
  },
  {
    keys: ["windhoek"],
    city: "Windhoek",
    country: "Namibia",
    region: "africa",
    lat: -22.5609,
    lng: 17.0658,
  },
  {
    keys: ["antananarivo", "madagascar"],
    city: "Antananarivo",
    country: "Madagascar",
    region: "africa",
    lat: -18.8792,
    lng: 47.5079,
  },
  {
    keys: ["freetown", "sierra leone"],
    city: "Freetown",
    country: "Sierra Leone",
    region: "africa",
    lat: 8.4657,
    lng: -13.2317,
  },
  {
    keys: ["monrovia", "liberia"],
    city: "Monrovia",
    country: "Liberia",
    region: "africa",
    lat: 6.3156,
    lng: -10.8074,
  },

  // ── Middle East (cities) ─────────────────────────────────────────
  {
    keys: ["dubai", "abu dhabi", "united arab emirates"],
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    keys: ["riyadh"],
    city: "Riyadh",
    country: "Saudi Arabia",
    region: "middle-east",
    lat: 24.7136,
    lng: 46.6753,
  },
  {
    keys: ["jeddah", "mecca", "medina"],
    city: "Jeddah",
    country: "Saudi Arabia",
    region: "middle-east",
    lat: 21.4858,
    lng: 39.1925,
  },
  {
    keys: ["tehran"],
    city: "Tehran",
    country: "Iran",
    region: "middle-east",
    lat: 35.6892,
    lng: 51.389,
  },
  {
    keys: ["isfahan", "esfahan"],
    city: "Isfahan",
    country: "Iran",
    region: "middle-east",
    lat: 32.6546,
    lng: 51.668,
  },
  {
    keys: ["tel aviv", "tel-aviv"],
    city: "Tel Aviv",
    country: "Israel",
    region: "middle-east",
    lat: 32.0853,
    lng: 34.7818,
  },
  {
    keys: ["haifa"],
    city: "Haifa",
    country: "Israel",
    region: "middle-east",
    lat: 32.794,
    lng: 34.9896,
  },
  {
    keys: ["jerusalem"],
    city: "Jerusalem",
    country: "Israel",
    region: "middle-east",
    lat: 31.7683,
    lng: 35.2137,
  },
  // Specific Gaza / West Bank pins — longer keys win over shorter ones
  {
    keys: ["gaza city"],
    city: "Gaza City",
    country: "Palestine",
    region: "middle-east",
    lat: 31.5017,
    lng: 34.4668,
  },
  {
    keys: ["gaza strip", "khan younis", "khan yunis", "rafah", "gaza"],
    city: "Gaza",
    country: "Palestine",
    region: "middle-east",
    lat: 31.3547,
    lng: 34.3088,
  },
  {
    keys: ["ramallah"],
    city: "Ramallah",
    country: "Palestine",
    region: "middle-east",
    lat: 31.9038,
    lng: 35.2034,
  },
  {
    keys: ["west bank", "hebron", "nablus", "jenin", "bethlehem"],
    city: "West Bank",
    country: "Palestine",
    region: "middle-east",
    lat: 31.9522,
    lng: 35.2332,
  },
  {
    keys: ["baghdad"],
    city: "Baghdad",
    country: "Iraq",
    region: "middle-east",
    lat: 33.3152,
    lng: 44.3661,
  },
  {
    keys: ["mosul"],
    city: "Mosul",
    country: "Iraq",
    region: "middle-east",
    lat: 36.335,
    lng: 43.1189,
  },
  {
    keys: ["basra", "basrah"],
    city: "Basra",
    country: "Iraq",
    region: "middle-east",
    lat: 30.5085,
    lng: 47.7804,
  },
  {
    keys: ["erbil", "irbil", "hawler"],
    city: "Erbil",
    country: "Iraq",
    region: "middle-east",
    lat: 36.1911,
    lng: 44.0092,
  },
  {
    keys: ["istanbul"],
    city: "Istanbul",
    country: "Turkey",
    region: "middle-east",
    lat: 41.0082,
    lng: 28.9784,
  },
  {
    keys: ["ankara"],
    city: "Ankara",
    country: "Turkey",
    region: "middle-east",
    lat: 39.9334,
    lng: 32.8597,
  },
  {
    keys: ["izmir"],
    city: "Izmir",
    country: "Turkey",
    region: "middle-east",
    lat: 38.4237,
    lng: 27.1428,
  },
  {
    keys: ["damascus"],
    city: "Damascus",
    country: "Syria",
    region: "middle-east",
    lat: 33.5138,
    lng: 36.2765,
  },
  {
    keys: ["aleppo"],
    city: "Aleppo",
    country: "Syria",
    region: "middle-east",
    lat: 36.2021,
    lng: 37.1343,
  },
  {
    keys: ["idlib"],
    city: "Idlib",
    country: "Syria",
    region: "middle-east",
    lat: 35.9306,
    lng: 36.6339,
  },
  {
    keys: ["homs"],
    city: "Homs",
    country: "Syria",
    region: "middle-east",
    lat: 34.7268,
    lng: 36.7234,
  },
  {
    keys: ["beirut"],
    city: "Beirut",
    country: "Lebanon",
    region: "middle-east",
    lat: 33.8938,
    lng: 35.5018,
  },
  {
    keys: ["amman"],
    city: "Amman",
    country: "Jordan",
    region: "middle-east",
    lat: 31.9454,
    lng: 35.9284,
  },
  {
    keys: ["doha"],
    city: "Doha",
    country: "Qatar",
    region: "middle-east",
    lat: 25.2854,
    lng: 51.531,
  },
  {
    keys: ["kuwait city", "kuwait"],
    city: "Kuwait City",
    country: "Kuwait",
    region: "middle-east",
    lat: 29.3759,
    lng: 47.9774,
  },
  {
    keys: ["manama", "bahrain"],
    city: "Manama",
    country: "Bahrain",
    region: "middle-east",
    lat: 26.2285,
    lng: 50.586,
  },
  {
    keys: ["muscat", "oman"],
    city: "Muscat",
    country: "Oman",
    region: "middle-east",
    lat: 23.588,
    lng: 58.3829,
  },
  {
    keys: ["sanaa", "sana'a"],
    city: "Sanaa",
    country: "Yemen",
    region: "middle-east",
    lat: 15.3694,
    lng: 44.191,
  },
  {
    keys: ["aden"],
    city: "Aden",
    country: "Yemen",
    region: "middle-east",
    lat: 12.7855,
    lng: 45.0187,
  },
  {
    keys: ["hodeidah", "hodeida", "al hudaydah"],
    city: "Hodeidah",
    country: "Yemen",
    region: "middle-east",
    lat: 14.7979,
    lng: 42.9545,
  },

  // ── Asia (cities) ────────────────────────────────────────────────
  {
    keys: ["beijing", "peking"],
    city: "Beijing",
    country: "China",
    region: "asia",
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    keys: ["shanghai"],
    city: "Shanghai",
    country: "China",
    region: "asia",
    lat: 31.2304,
    lng: 121.4737,
  },
  {
    keys: ["hong kong"],
    city: "Hong Kong",
    country: "China",
    region: "asia",
    lat: 22.3193,
    lng: 114.1694,
  },
  {
    keys: ["macau", "macao"],
    city: "Macau",
    country: "China",
    region: "asia",
    lat: 22.1987,
    lng: 113.5439,
  },
  {
    keys: ["guangzhou", "canton"],
    city: "Guangzhou",
    country: "China",
    region: "asia",
    lat: 23.1291,
    lng: 113.2644,
  },
  {
    keys: ["shenzhen"],
    city: "Shenzhen",
    country: "China",
    region: "asia",
    lat: 22.5431,
    lng: 114.0579,
  },
  {
    keys: ["wuhan"],
    city: "Wuhan",
    country: "China",
    region: "asia",
    lat: 30.5928,
    lng: 114.3055,
  },
  {
    keys: ["chengdu"],
    city: "Chengdu",
    country: "China",
    region: "asia",
    lat: 30.5728,
    lng: 104.0668,
  },
  {
    keys: ["xi'an", "xian"],
    city: "Xi'an",
    country: "China",
    region: "asia",
    lat: 34.3416,
    lng: 108.9398,
  },
  {
    keys: ["taipei", "taiwan"],
    city: "Taipei",
    country: "Taiwan",
    region: "asia",
    lat: 25.033,
    lng: 121.5654,
  },
  {
    keys: ["tokyo"],
    city: "Tokyo",
    country: "Japan",
    region: "asia",
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    keys: ["osaka"],
    city: "Osaka",
    country: "Japan",
    region: "asia",
    lat: 34.6937,
    lng: 135.5023,
  },
  {
    keys: ["kyoto"],
    city: "Kyoto",
    country: "Japan",
    region: "asia",
    lat: 35.0116,
    lng: 135.7681,
  },
  {
    keys: ["seoul"],
    city: "Seoul",
    country: "South Korea",
    region: "asia",
    lat: 37.5665,
    lng: 126.978,
  },
  {
    keys: ["busan", "pusan"],
    city: "Busan",
    country: "South Korea",
    region: "asia",
    lat: 35.1796,
    lng: 129.0756,
  },
  {
    keys: ["pyongyang", "north korea"],
    city: "Pyongyang",
    country: "North Korea",
    region: "asia",
    lat: 39.0392,
    lng: 125.7625,
  },
  {
    keys: ["new delhi", "delhi"],
    city: "Delhi",
    country: "India",
    region: "asia",
    lat: 28.6139,
    lng: 77.209,
  },
  {
    keys: ["mumbai", "bombay"],
    city: "Mumbai",
    country: "India",
    region: "asia",
    lat: 19.076,
    lng: 72.8777,
  },
  {
    keys: ["bangalore", "bengaluru"],
    city: "Bengaluru",
    country: "India",
    region: "asia",
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    keys: ["kolkata", "calcutta"],
    city: "Kolkata",
    country: "India",
    region: "asia",
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    keys: ["chennai", "madras"],
    city: "Chennai",
    country: "India",
    region: "asia",
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    keys: ["hyderabad"],
    city: "Hyderabad",
    country: "India",
    region: "asia",
    lat: 17.385,
    lng: 78.4867,
  },
  {
    keys: ["ahmedabad"],
    city: "Ahmedabad",
    country: "India",
    region: "asia",
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    keys: ["islamabad"],
    city: "Islamabad",
    country: "Pakistan",
    region: "asia",
    lat: 33.6844,
    lng: 73.0479,
  },
  {
    keys: ["rawalpindi"],
    city: "Rawalpindi",
    country: "Pakistan",
    region: "asia",
    lat: 33.5651,
    lng: 73.0169,
  },
  {
    keys: ["karachi"],
    city: "Karachi",
    country: "Pakistan",
    region: "asia",
    lat: 24.8607,
    lng: 67.0011,
  },
  {
    keys: ["lahore"],
    city: "Lahore",
    country: "Pakistan",
    region: "asia",
    lat: 31.5204,
    lng: 74.3587,
  },
  {
    keys: ["peshawar"],
    city: "Peshawar",
    country: "Pakistan",
    region: "asia",
    lat: 34.0151,
    lng: 71.5249,
  },
  {
    keys: ["quetta"],
    city: "Quetta",
    country: "Pakistan",
    region: "asia",
    lat: 30.1798,
    lng: 66.975,
  },
  {
    keys: ["kabul"],
    city: "Kabul",
    country: "Afghanistan",
    region: "asia",
    lat: 34.5553,
    lng: 69.2075,
  },
  {
    keys: ["kandahar"],
    city: "Kandahar",
    country: "Afghanistan",
    region: "asia",
    lat: 31.6289,
    lng: 65.7372,
  },
  {
    keys: ["singapore"],
    city: "Singapore",
    country: "Singapore",
    region: "asia",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    keys: ["jakarta"],
    city: "Jakarta",
    country: "Indonesia",
    region: "asia",
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    keys: ["bali", "denpasar"],
    city: "Denpasar",
    country: "Indonesia",
    region: "asia",
    lat: -8.6705,
    lng: 115.2126,
  },
  {
    keys: ["manila"],
    city: "Manila",
    country: "Philippines",
    region: "asia",
    lat: 14.5995,
    lng: 120.9842,
  },
  {
    keys: ["bangkok"],
    city: "Bangkok",
    country: "Thailand",
    region: "asia",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    keys: ["hanoi", "ha noi"],
    city: "Hanoi",
    country: "Vietnam",
    region: "asia",
    lat: 21.0278,
    lng: 105.8342,
  },
  {
    keys: ["ho chi minh", "saigon"],
    city: "Ho Chi Minh City",
    country: "Vietnam",
    region: "asia",
    lat: 10.8231,
    lng: 106.6297,
  },
  {
    keys: ["kuala lumpur"],
    city: "Kuala Lumpur",
    country: "Malaysia",
    region: "asia",
    lat: 3.139,
    lng: 101.6869,
  },
  {
    keys: ["dhaka"],
    city: "Dhaka",
    country: "Bangladesh",
    region: "asia",
    lat: 23.8103,
    lng: 90.4125,
  },
  {
    keys: ["chittagong", "chattogram"],
    city: "Chittagong",
    country: "Bangladesh",
    region: "asia",
    lat: 22.3569,
    lng: 91.7832,
  },
  {
    keys: ["colombo"],
    city: "Colombo",
    country: "Sri Lanka",
    region: "asia",
    lat: 6.9271,
    lng: 79.8612,
  },
  {
    keys: ["kathmandu"],
    city: "Kathmandu",
    country: "Nepal",
    region: "asia",
    lat: 27.7172,
    lng: 85.324,
  },
  {
    keys: ["thimphu", "bhutan"],
    city: "Thimphu",
    country: "Bhutan",
    region: "asia",
    lat: 27.4728,
    lng: 89.6393,
  },
  {
    keys: ["malé", "male", "maldives"],
    city: "Malé",
    country: "Maldives",
    region: "asia",
    lat: 4.1755,
    lng: 73.5093,
  },
  {
    keys: ["yangon", "naypyidaw", "myanmar", "burma"],
    city: "Yangon",
    country: "Myanmar",
    region: "asia",
    lat: 16.8661,
    lng: 96.1951,
  },
  {
    keys: ["phnom penh"],
    city: "Phnom Penh",
    country: "Cambodia",
    region: "asia",
    lat: 11.5564,
    lng: 104.9282,
  },
  {
    keys: ["vientiane", "laos"],
    city: "Vientiane",
    country: "Laos",
    region: "asia",
    lat: 17.9757,
    lng: 102.6331,
  },
  {
    keys: ["ulaanbaatar", "ulan bator", "mongolia"],
    city: "Ulaanbaatar",
    country: "Mongolia",
    region: "asia",
    lat: 47.8864,
    lng: 106.9057,
  },
  {
    keys: ["tashkent", "uzbekistan"],
    city: "Tashkent",
    country: "Uzbekistan",
    region: "asia",
    lat: 41.2995,
    lng: 69.2401,
  },
  {
    keys: ["almaty"],
    city: "Almaty",
    country: "Kazakhstan",
    region: "asia",
    lat: 43.222,
    lng: 76.8512,
  },
  {
    keys: ["astana", "nur-sultan", "nursultan"],
    city: "Astana",
    country: "Kazakhstan",
    region: "asia",
    lat: 51.1694,
    lng: 71.4491,
  },
  {
    keys: ["bishkek", "kyrgyzstan"],
    city: "Bishkek",
    country: "Kyrgyzstan",
    region: "asia",
    lat: 42.8746,
    lng: 74.5698,
  },
  {
    keys: ["dushanbe", "tajikistan"],
    city: "Dushanbe",
    country: "Tajikistan",
    region: "asia",
    lat: 38.5598,
    lng: 68.787,
  },
  {
    keys: ["ashgabat", "turkmenistan"],
    city: "Ashgabat",
    country: "Turkmenistan",
    region: "asia",
    lat: 37.9601,
    lng: 58.3261,
  },

  // ── Oceania (cities) ─────────────────────────────────────────────
  {
    keys: ["sydney"],
    city: "Sydney",
    country: "Australia",
    region: "oceania",
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    keys: ["melbourne"],
    city: "Melbourne",
    country: "Australia",
    region: "oceania",
    lat: -37.8136,
    lng: 144.9631,
  },
  {
    keys: ["canberra"],
    city: "Canberra",
    country: "Australia",
    region: "oceania",
    lat: -35.2809,
    lng: 149.13,
  },
  {
    keys: ["brisbane"],
    city: "Brisbane",
    country: "Australia",
    region: "oceania",
    lat: -27.4698,
    lng: 153.0251,
  },
  {
    keys: ["perth"],
    city: "Perth",
    country: "Australia",
    region: "oceania",
    lat: -31.9505,
    lng: 115.8605,
  },
  {
    keys: ["auckland"],
    city: "Auckland",
    country: "New Zealand",
    region: "oceania",
    lat: -36.8509,
    lng: 174.7645,
  },
  {
    keys: ["wellington"],
    city: "Wellington",
    country: "New Zealand",
    region: "oceania",
    lat: -41.2865,
    lng: 174.7762,
  },
  {
    keys: ["christchurch"],
    city: "Christchurch",
    country: "New Zealand",
    region: "oceania",
    lat: -43.5321,
    lng: 172.6362,
  },
  {
    keys: ["honolulu", "hawaii"],
    city: "Honolulu",
    country: "United States",
    region: "oceania",
    lat: 21.3069,
    lng: -157.8583,
  },
  {
    keys: ["suva", "fiji"],
    city: "Suva",
    country: "Fiji",
    region: "oceania",
    lat: -18.1416,
    lng: 178.4419,
  },
  {
    keys: ["port moresby", "papua new guinea"],
    city: "Port Moresby",
    country: "Papua New Guinea",
    region: "oceania",
    lat: -9.4438,
    lng: 147.1803,
  },

  // ── Country-level fallbacks (shorter / broader keys) ─────────────
  {
    keys: ["united kingdom", "britain", "british", "england", "scotland", "wales", "uk "],
    city: "London",
    country: "United Kingdom",
    region: "europe",
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    keys: ["france", "french"],
    city: "Paris",
    country: "France",
    region: "europe",
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    keys: ["germany", "german"],
    city: "Berlin",
    country: "Germany",
    region: "europe",
    lat: 52.52,
    lng: 13.405,
  },
  {
    keys: ["russia", "russian"],
    city: "Moscow",
    country: "Russia",
    region: "europe",
    lat: 55.7558,
    lng: 37.6173,
  },
  {
    keys: ["ukraine", "ukrainian"],
    city: "Kyiv",
    country: "Ukraine",
    region: "europe",
    lat: 50.4501,
    lng: 30.5234,
  },
  {
    keys: ["poland", "polish"],
    city: "Warsaw",
    country: "Poland",
    region: "europe",
    lat: 52.2297,
    lng: 21.0122,
  },
  {
    keys: ["italy", "italian"],
    city: "Rome",
    country: "Italy",
    region: "europe",
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    keys: ["spain", "spanish"],
    city: "Madrid",
    country: "Spain",
    region: "europe",
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    keys: ["belgium"],
    city: "Brussels",
    country: "Belgium",
    region: "europe",
    lat: 50.8503,
    lng: 4.3517,
  },
  {
    keys: ["netherlands", "dutch"],
    city: "Amsterdam",
    country: "Netherlands",
    region: "europe",
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    keys: ["europe", "european union", "eu ", "nato"],
    city: "Brussels",
    country: "Belgium",
    region: "europe",
    lat: 50.8503,
    lng: 4.3517,
  },
  {
    keys: ["united states", "u.s.", "u.s.a", "usa", "american", "america"],
    city: "Washington",
    country: "United States",
    region: "americas",
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    keys: ["mexico", "mexican"],
    city: "Mexico City",
    country: "Mexico",
    region: "americas",
    lat: 19.4326,
    lng: -99.1332,
  },
  {
    keys: ["brazil", "brazilian"],
    city: "São Paulo",
    country: "Brazil",
    region: "americas",
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    keys: ["argentina", "argentine"],
    city: "Buenos Aires",
    country: "Argentina",
    region: "americas",
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    keys: ["canada", "canadian"],
    city: "Ottawa",
    country: "Canada",
    region: "americas",
    lat: 45.4215,
    lng: -75.6972,
  },
  {
    keys: ["colombia", "colombian"],
    city: "Bogotá",
    country: "Colombia",
    region: "americas",
    lat: 4.711,
    lng: -74.0721,
  },
  {
    keys: ["peru", "peruvian"],
    city: "Lima",
    country: "Peru",
    region: "americas",
    lat: -12.0464,
    lng: -77.0428,
  },
  {
    keys: ["chile", "chilean"],
    city: "Santiago",
    country: "Chile",
    region: "americas",
    lat: -33.4489,
    lng: -70.6693,
  },
  {
    keys: ["venezuela", "venezuelan"],
    city: "Caracas",
    country: "Venezuela",
    region: "americas",
    lat: 10.4806,
    lng: -66.9036,
  },
  {
    keys: ["cuba", "cuban"],
    city: "Havana",
    country: "Cuba",
    region: "americas",
    lat: 23.1136,
    lng: -82.3666,
  },
  {
    keys: ["latin america", "south america", "central america"],
    city: "São Paulo",
    country: "Brazil",
    region: "americas",
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    keys: ["egypt", "egyptian"],
    city: "Cairo",
    country: "Egypt",
    region: "africa",
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    keys: ["nigeria", "nigerian"],
    city: "Lagos",
    country: "Nigeria",
    region: "africa",
    lat: 6.5244,
    lng: 3.3792,
  },
  {
    keys: ["kenya", "kenyan"],
    city: "Nairobi",
    country: "Kenya",
    region: "africa",
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    keys: ["south africa", "south african"],
    city: "Johannesburg",
    country: "South Africa",
    region: "africa",
    lat: -26.2041,
    lng: 28.0473,
  },
  {
    keys: ["ethiopia", "ethiopian"],
    city: "Addis Ababa",
    country: "Ethiopia",
    region: "africa",
    lat: 9.032,
    lng: 38.7469,
  },
  {
    keys: ["ghana", "ghanaian"],
    city: "Accra",
    country: "Ghana",
    region: "africa",
    lat: 5.6037,
    lng: -0.187,
  },
  {
    keys: ["congo", "congolese", "drc"],
    city: "Kinshasa",
    country: "DR Congo",
    region: "africa",
    lat: -4.4419,
    lng: 15.2663,
  },
  {
    keys: ["sudan", "sudanese"],
    city: "Khartoum",
    country: "Sudan",
    region: "africa",
    lat: 15.5007,
    lng: 32.5599,
  },
  {
    keys: ["morocco", "moroccan"],
    city: "Rabat",
    country: "Morocco",
    region: "africa",
    lat: 34.0209,
    lng: -6.8416,
  },
  {
    keys: ["libya", "libyan"],
    city: "Tripoli",
    country: "Libya",
    region: "africa",
    lat: 32.8872,
    lng: 13.1913,
  },
  {
    keys: ["africa", "african"],
    city: "Nairobi",
    country: "Kenya",
    region: "africa",
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    keys: ["saudi arabia", "saudi"],
    city: "Riyadh",
    country: "Saudi Arabia",
    region: "middle-east",
    lat: 24.7136,
    lng: 46.6753,
  },
  {
    keys: ["iran", "iranian"],
    city: "Tehran",
    country: "Iran",
    region: "middle-east",
    lat: 35.6892,
    lng: 51.389,
  },
  {
    keys: ["israel", "israeli"],
    city: "Tel Aviv",
    country: "Israel",
    region: "middle-east",
    lat: 32.0853,
    lng: 34.7818,
  },
  {
    keys: ["palestine", "palestinian"],
    city: "Gaza",
    country: "Palestine",
    region: "middle-east",
    lat: 31.5017,
    lng: 34.4668,
  },
  {
    keys: ["iraq", "iraqi"],
    city: "Baghdad",
    country: "Iraq",
    region: "middle-east",
    lat: 33.3152,
    lng: 44.3661,
  },
  {
    keys: ["turkey", "turkish", "türkiye", "turkiye"],
    city: "Ankara",
    country: "Turkey",
    region: "middle-east",
    lat: 39.9334,
    lng: 32.8597,
  },
  {
    keys: ["syria", "syrian"],
    city: "Damascus",
    country: "Syria",
    region: "middle-east",
    lat: 33.5138,
    lng: 36.2765,
  },
  {
    keys: ["lebanon", "lebanese"],
    city: "Beirut",
    country: "Lebanon",
    region: "middle-east",
    lat: 33.8938,
    lng: 35.5018,
  },
  {
    keys: ["qatar", "qatari"],
    city: "Doha",
    country: "Qatar",
    region: "middle-east",
    lat: 25.2854,
    lng: 51.531,
  },
  {
    keys: ["yemen", "yemeni"],
    city: "Sanaa",
    country: "Yemen",
    region: "middle-east",
    lat: 15.3694,
    lng: 44.191,
  },
  {
    keys: ["uae", "emirates"],
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    keys: ["middle east", "middle-east"],
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    keys: ["china", "chinese"],
    city: "Beijing",
    country: "China",
    region: "asia",
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    keys: ["japan", "japanese"],
    city: "Tokyo",
    country: "Japan",
    region: "asia",
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    keys: ["south korea", "korea", "korean"],
    city: "Seoul",
    country: "South Korea",
    region: "asia",
    lat: 37.5665,
    lng: 126.978,
  },
  {
    keys: ["india", "indian"],
    city: "Delhi",
    country: "India",
    region: "asia",
    lat: 28.6139,
    lng: 77.209,
  },
  {
    keys: ["pakistan", "pakistani"],
    city: "Islamabad",
    country: "Pakistan",
    region: "asia",
    lat: 33.6844,
    lng: 73.0479,
  },
  {
    keys: ["afghanistan", "afghan"],
    city: "Kabul",
    country: "Afghanistan",
    region: "asia",
    lat: 34.5553,
    lng: 69.2075,
  },
  {
    keys: ["indonesia", "indonesian"],
    city: "Jakarta",
    country: "Indonesia",
    region: "asia",
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    keys: ["philippines", "filipino", "philippine"],
    city: "Manila",
    country: "Philippines",
    region: "asia",
    lat: 14.5995,
    lng: 120.9842,
  },
  {
    keys: ["thailand", "thai"],
    city: "Bangkok",
    country: "Thailand",
    region: "asia",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    keys: ["vietnam", "vietnamese"],
    city: "Hanoi",
    country: "Vietnam",
    region: "asia",
    lat: 21.0278,
    lng: 105.8342,
  },
  {
    keys: ["bangladesh", "bangladeshi"],
    city: "Dhaka",
    country: "Bangladesh",
    region: "asia",
    lat: 23.8103,
    lng: 90.4125,
  },
  {
    keys: ["sri lanka", "sri lankan"],
    city: "Colombo",
    country: "Sri Lanka",
    region: "asia",
    lat: 6.9271,
    lng: 79.8612,
  },
  {
    keys: ["kazakhstan", "kazakh"],
    city: "Astana",
    country: "Kazakhstan",
    region: "asia",
    lat: 51.1694,
    lng: 71.4491,
  },
  {
    keys: ["asia", "asian"],
    city: "Singapore",
    country: "Singapore",
    region: "asia",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    keys: ["australia", "australian"],
    city: "Sydney",
    country: "Australia",
    region: "oceania",
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    keys: ["new zealand", "zealand", "kiwi"],
    city: "Auckland",
    country: "New Zealand",
    region: "oceania",
    lat: -36.8509,
    lng: 174.7645,
  },
  {
    keys: ["oceania", "pacific islands", "pacific"],
    city: "Sydney",
    country: "Australia",
    region: "oceania",
    lat: -33.8688,
    lng: 151.2093,
  },

];

const GLOBAL_FALLBACK: InferredGeo = {
  region: "global",
  city: "Global",
  country: "World",
  lat: 20,
  lng: 0,
};

/** Flatten keys → place, sorted longest key first for specificity. */
const KEY_INDEX: { key: string; place: GeoPlace }[] = GEO_PLACES.flatMap(
  (place) => place.keys.map((key) => ({ key: key.toLowerCase(), place })),
).sort((a, b) => b.key.length - a.key.length);

/** Deterministic 32-bit hash of a string (FNV-1a style). */
function hashString(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * Slightly offset lat/lng by up to ±0.3° using a stable hash of `seed`
 * so multiple stories in the same city do not stack on one pixel.
 */
export function jitterLatLng(
  lat: number,
  lng: number,
  seed: string,
): { lat: number; lng: number } {
  const h = hashString(seed);
  const jLat = (((h & 0xffff) / 0xffff) * 2 - 1) * 0.3;
  const jLng = ((((h >>> 16) & 0xffff) / 0xffff) * 2 - 1) * 0.3;
  const nextLat = Math.max(-90, Math.min(90, lat + jLat));
  const nextLng = ((lng + jLng + 540) % 360) - 180;
  return { lat: nextLat, lng: nextLng };
}

/**
 * Infer region / city / country / coordinates from free text.
 * Matches the longest (most specific) key first, then jitters lat/lng
 * by ±0.3° using a hash of `jitterSeed` (prefer article title) so
 * co-located stories do not stack on one map pin.
 */
export function inferGeoFromText(
  text: string,
  jitterSeed?: string,
): InferredGeo {
  const t = text.toLowerCase();
  let matched: GeoPlace | null = null;

  for (const entry of KEY_INDEX) {
    if (t.includes(entry.key)) {
      matched = entry.place;
      break;
    }
  }

  const base = matched
    ? {
        region: matched.region,
        city: matched.city,
        country: matched.country,
        lat: matched.lat,
        lng: matched.lng,
      }
    : { ...GLOBAL_FALLBACK };

  const seed = (jitterSeed && jitterSeed.trim()) || text;
  const { lat, lng } = jitterLatLng(base.lat, base.lng, seed);
  return { ...base, lat, lng };
}

function isDefaultCoords(lat?: number, lng?: number): boolean {
  if (lat == null || lng == null) return true;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return true;
  // AI / legacy default pin (Gulf of Guinea-ish)
  return Number(lat) === 20 && Number(lng) === 0;
}

function isPlaceholderCity(city?: string): boolean {
  const c = (city || "").trim().toLowerCase();
  return !c || c === "global" || c === "world" || c === "unknown";
}

function isPlaceholderCountry(country?: string): boolean {
  const c = (country || "").trim().toLowerCase();
  return !c || c === "world" || c === "global" || c === "unknown";
}

/**
 * Fill missing / placeholder geo fields on AI-generated (or partial) drafts
 * using place matching over free text. Existing specific values are kept.
 */
export function fillMissingGeoFromText(
  current: {
    region?: RegionId;
    city?: string;
    country?: string;
    lat?: number;
    lng?: number;
  },
  text: string,
  jitterSeed?: string,
): InferredGeo {
  const inferred = inferGeoFromText(text, jitterSeed ?? current.city);

  const cityMissing = isPlaceholderCity(current.city);
  const countryMissing = isPlaceholderCountry(current.country);
  const coordsMissing = isDefaultCoords(current.lat, current.lng);
  const regionMissing =
    !current.region || current.region === "global";

  // Nothing useful to fill and coords already specific — keep as-is
  if (!cityMissing && !countryMissing && !coordsMissing) {
    return {
      region: (current.region as RegionId) || "global",
      city: current.city as string,
      country: current.country as string,
      lat: Number(current.lat),
      lng: Number(current.lng),
    };
  }

  return {
    region: regionMissing ? inferred.region : (current.region as RegionId),
    city: cityMissing ? inferred.city : (current.city as string),
    country: countryMissing ? inferred.country : (current.country as string),
    lat: coordsMissing ? inferred.lat : Number(current.lat),
    lng: coordsMissing ? inferred.lng : Number(current.lng),
  };
}
