import type { Article } from "./types";

const sample = (topic: string) => [
  `${topic} is reshaping how capitals, companies, and citizens coordinate across borders. Analysts on the World Grid are tracking second-order effects: supply chains, public trust, and the next cycle of regulation.`,
  `Local sources describe a mix of urgency and fatigue. Infrastructure is strained in some corridors while capital races ahead in others. The map no longer moves in straight lines — shocks in one cell cascade into neighboring regions within hours.`,
  `What matters next is not a single headline, but the topology: which nodes are resilient, which alliances harden, and which narratives travel faster than policy. World Grid will keep this cell updated as primary sources verify.`,
  `For readers building products, portfolios, or public strategy, the practical takeaway is simple: treat geography as a first-class signal. Time zones, ports, undersea cables, and diaspora networks now move markets as much as interest rates.`,
];

/** Seed corpus used when data/articles.json is missing. */
export const SEED_ARTICLES: Article[] = [
  {
    id: "1",
    slug: "ai-corridors-redraw-pacific-trade",
    title: "AI corridors redraw Pacific trade routes",
    dek: "Compute campuses, undersea cables, and export controls are turning the Pacific into the decade’s most contested economic grid.",
    content: sample("A new generation of AI infrastructure corridors across the Pacific"),
    category: "technology",
    region: "asia",
    city: "Singapore",
    country: "Singapore",
    lat: 1.35,
    lng: 103.82,
    author: "Mira Chen",
    publishedAt: "2026-07-31T08:20:00.000Z",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Earth from orbit with illuminated city networks",
    featured: true,
    breaking: true,
    tags: ["AI", "trade", "infrastructure", "Pacific"],
    status: "published",
  },
  {
    id: "2",
    slug: "sahara-green-hydrogen-hubs-scale",
    title: "Sahara green-hydrogen hubs hit commercial scale",
    dek: "North African energy megaprojects are shipping first offtake cargoes toward European industrial buyers.",
    content: sample("Commercial-scale green hydrogen production across the Sahara belt"),
    category: "climate",
    region: "africa",
    city: "Casablanca",
    country: "Morocco",
    lat: 33.57,
    lng: -7.59,
    author: "Amira Benali",
    publishedAt: "2026-07-30T14:10:00.000Z",
    image:
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Solar panels in a desert landscape at dusk",
    featured: true,
    tags: ["hydrogen", "energy", "Africa", "EU"],
    status: "published",
  },
  {
    id: "3",
    slug: "brussels-agentic-ai-act-enforcement",
    title: "Brussels begins Agentic AI Act enforcement wave",
    dek: "The first compliance audits target high-autonomy systems used in finance, logistics, and public services.",
    content: sample("Europe’s Agentic AI Act moving from statute to live enforcement"),
    category: "politics",
    region: "europe",
    city: "Brussels",
    country: "Belgium",
    lat: 50.85,
    lng: 4.35,
    author: "Elena Vogt",
    publishedAt: "2026-07-30T09:45:00.000Z",
    image:
      "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "European Parliament exterior",
    tags: ["regulation", "AI", "EU", "compliance"],
    status: "published",
  },
  {
    id: "4",
    slug: "gulf-sovereign-funds-back-robotics",
    title: "Gulf sovereign funds pile into industrial robotics",
    dek: "Diversification strategies are shifting from real estate and sports to factory automation and dual-use hardware.",
    content: sample("Gulf sovereign capital reallocating into industrial robotics"),
    category: "business",
    region: "middle-east",
    city: "Abu Dhabi",
    country: "UAE",
    lat: 24.45,
    lng: 54.37,
    author: "Rashid Al-Najjar",
    publishedAt: "2026-07-29T16:30:00.000Z",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Industrial robot arms on a factory floor",
    tags: ["sovereign wealth", "robotics", "Gulf"],
    status: "published",
  },
  {
    id: "5",
    slug: "amazon-basin-carbon-markets-reboot",
    title: "Amazon basin carbon markets attempt a credibility reboot",
    dek: "New satellite verification standards aim to restore trust after years of questionable offsets.",
    content: sample("Carbon market reforms across the Amazon basin"),
    category: "climate",
    region: "americas",
    city: "Manaus",
    country: "Brazil",
    lat: -3.12,
    lng: -60.02,
    author: "Lucia Ferreira",
    publishedAt: "2026-07-29T11:05:00.000Z",
    image:
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Aerial view of Amazon rainforest canopy",
    tags: ["carbon", "Amazon", "climate finance"],
    status: "published",
  },
  {
    id: "6",
    slug: "sydney-quantum-network-live",
    title: "Sydney lights up a city-scale quantum network",
    dek: "Researchers demonstrate entanglement distribution across metro fiber — a stepping stone to quantum-secure finance rails.",
    content: sample("A metro-scale quantum network demonstration in Sydney"),
    category: "science",
    region: "oceania",
    city: "Sydney",
    country: "Australia",
    lat: -33.87,
    lng: 151.21,
    author: "James Okonkwo",
    publishedAt: "2026-07-28T22:15:00.000Z",
    image:
      "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Abstract quantum visualization of light particles",
    featured: true,
    tags: ["quantum", "Australia", "security"],
    status: "published",
  },
  {
    id: "7",
    slug: "nairobi-fintech-corridor-expands",
    title: "Nairobi’s fintech corridor expands into pan-African settlement",
    dek: "Real-time rails and mobile money interoperabilty are compressing remittance costs across the continent.",
    content: sample("Pan-African settlement rails expanding from Nairobi"),
    category: "business",
    region: "africa",
    city: "Nairobi",
    country: "Kenya",
    lat: -1.29,
    lng: 36.82,
    author: "Wanjiru Mwangi",
    publishedAt: "2026-07-28T13:40:00.000Z",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Person using mobile payment on a smartphone",
    tags: ["fintech", "Africa", "payments"],
    status: "published",
  },
  {
    id: "8",
    slug: "arctic-shipping-lanes-open-earlier",
    title: "Arctic shipping lanes open earlier than forecast",
    dek: "Insurers, navies, and logistics firms scramble as seasonal windows stretch — and geopolitical risk maps redraw.",
    content: sample("Earlier seasonal openings of Arctic shipping corridors"),
    category: "security",
    region: "global",
    city: "Tromsø",
    country: "Norway",
    lat: 69.65,
    lng: 18.96,
    author: "Erik Nilsen",
    publishedAt: "2026-07-27T18:00:00.000Z",
    image:
      "https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Arctic ice and open water under cold light",
    tags: ["Arctic", "shipping", "geopolitics"],
    status: "published",
  },
  {
    id: "9",
    slug: "tokyo-culture-tech-exports-record",
    title: "Tokyo’s culture-tech exports hit another record year",
    dek: "From interactive series to AI-assisted studios, Japanese soft power is becoming an export platform, not just a trend.",
    content: sample("Japan’s culture-tech industry setting new export records"),
    category: "culture",
    region: "asia",
    city: "Tokyo",
    country: "Japan",
    lat: 35.68,
    lng: 139.69,
    author: "Hana Park",
    publishedAt: "2026-07-27T07:25:00.000Z",
    image:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Tokyo city skyline at dusk",
    tags: ["Japan", "media", "exports", "soft power"],
    status: "published",
  },
  {
    id: "10",
    slug: "mexico-nearshoring-chip-packaging",
    title: "Mexico’s nearshoring wave reaches chip packaging",
    dek: "US-aligned supply chains are adding advanced packaging capacity south of the border — with water and power as the real bottlenecks.",
    content: sample("Advanced chip packaging capacity expanding in Mexico"),
    category: "technology",
    region: "americas",
    city: "Guadalajara",
    country: "Mexico",
    lat: 20.66,
    lng: -103.35,
    author: "Diego Morales",
    publishedAt: "2026-07-26T15:50:00.000Z",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Close-up of a semiconductor circuit board",
    tags: ["semiconductors", "nearshoring", "Mexico"],
    status: "published",
  },
  {
    id: "11",
    slug: "london-ai-labor-compact",
    title: "London brokers an AI labor compact for creative industries",
    dek: "Unions, studios, and platforms test a royalty-plus-consent model that could travel beyond the UK.",
    content: sample("A UK-led labor compact covering AI use in creative industries"),
    category: "culture",
    region: "europe",
    city: "London",
    country: "United Kingdom",
    lat: 51.51,
    lng: -0.13,
    author: "Priya Shah",
    publishedAt: "2026-07-26T10:00:00.000Z",
    image:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "London skyline along the Thames",
    tags: ["labor", "AI", "creative economy"],
    status: "published",
  },
  {
    id: "12",
    slug: "global-grid-cyber-drill-results",
    title: "Global cyber drill exposes weak links in city grids",
    dek: "A 48-nation simulation headquartered in New York found cascading failures where OT networks still trust flat perimeter models.",
    content: sample("Results from a multi-nation critical infrastructure cyber drill"),
    category: "security",
    region: "americas",
    city: "New York",
    country: "United States",
    lat: 40.71,
    lng: -74.01,
    author: "Noah Keller",
    publishedAt: "2026-07-25T19:30:00.000Z",
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Abstract cybersecurity network visualization",
    tags: ["cyber", "infrastructure", "OT", "New York"],
    status: "published",
  },
];
