import { createHash } from "crypto";
import { promises as fs } from "fs";
import path from "path";
import { SITE } from "./constants";
import { SEED_ARTICLES } from "./seed-articles";
import { DEFAULT_SITE_SEO } from "./seo";
import type {
  Article,
  ArticleInput,
  SiteSettings,
  Subscriber,
} from "./types";

const DATA_DIR = path.join(process.cwd(), "data");
const ARTICLES_FILE = path.join(DATA_DIR, "articles.json");
const SETTINGS_FILE = path.join(DATA_DIR, "settings.json");
const SUBSCRIBERS_FILE = path.join(DATA_DIR, "subscribers.json");

const DEFAULT_SETTINGS: SiteSettings = {
  homepageLayout: "classic",
  autoSyncEnabled: true,
  autoSyncIntervalMinutes: 30,
  lastSyncAt: null,
  lastSyncResult: null,
  siteName: SITE.name,
  tagline: SITE.tagline,
  defaultAiProvider: "gemini",
  seo: DEFAULT_SITE_SEO,
};

async function ensureDataDir() {
  await fs.mkdir(DATA_DIR, { recursive: true });
}

async function readJson<T>(file: string, fallback: T): Promise<T> {
  try {
    const raw = await fs.readFile(file, "utf8");
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

async function writeJson<T>(file: string, data: T) {
  await ensureDataDir();
  await fs.writeFile(file, JSON.stringify(data, null, 2), "utf8");
}

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

export async function getSettings(): Promise<SiteSettings> {
  const settings = await readJson<SiteSettings>(SETTINGS_FILE, DEFAULT_SETTINGS);
  return {
    ...DEFAULT_SETTINGS,
    ...settings,
    seo: { ...DEFAULT_SITE_SEO, ...DEFAULT_SETTINGS.seo, ...settings.seo },
  };
}

export async function saveSettings(
  patch: Partial<SiteSettings>,
): Promise<SiteSettings> {
  const current = await getSettings();
  const next = { ...current, ...patch };
  await writeJson(SETTINGS_FILE, next);
  return next;
}

/**
 * Remove duplicate ids/slugs/sourceUrls. Keeps the newest publishedAt entry.
 * Also repairs legacy truncated auto_ ids (base64 URL prefixes) so React keys stay unique.
 */
export function dedupeArticles(articles: Article[]): {
  articles: Article[];
  changed: boolean;
} {
  let changed = false;

  function repairId(article: Article): Article {
    // Old bug: id = base64url(url).slice(0, 24) → many Al Jazeera URLs shared the same prefix
    // e.g. auto_aHR0cHM6Ly93d3cuYWxqYXpl  (== base64 of "https://www.aljaze")
    const seed =
      article.sourceUrl ||
      (article.autoGenerated
        ? `${article.source || "wire"}:${article.title}:${article.publishedAt}:${article.slug}`
        : null);

    if (!seed) return article;

    const hash = createHash("sha256").update(seed).digest("hex").slice(0, 16);
    const fixedId = `auto_${hash}`;
    const isHexAuto =
      article.id.startsWith("auto_") &&
      /^[a-f0-9]{16}$/.test(article.id.slice(5));

    // Always normalize auto/wire items, and any legacy truncated-base64 ids
    const shouldRepair =
      article.autoGenerated ||
      article.id.startsWith("auto_aHR0c") ||
      (article.id.startsWith("auto_") && !isHexAuto);

    if (shouldRepair && fixedId !== article.id) {
      changed = true;
      return { ...article, id: fixedId };
    }
    return article;
  }

  const newestFirst = [...articles]
    .map(repairId)
    .sort((a, b) => +new Date(b.publishedAt) - +new Date(a.publishedAt));

  const seenIds = new Set<string>();
  const seenSources = new Set<string>();
  const seenSlugs = new Set<string>();
  const result: Article[] = [];

  for (const article of newestFirst) {
    if (seenIds.has(article.id)) {
      changed = true;
      continue;
    }
    if (article.sourceUrl && seenSources.has(article.sourceUrl)) {
      changed = true;
      continue;
    }

    let next = article;
    if (seenSlugs.has(article.slug)) {
      const suffix = article.id.replace(/^auto_/, "").slice(0, 8);
      next = { ...article, slug: `${article.slug}-${suffix}` };
      changed = true;
    }

    seenIds.add(next.id);
    if (next.sourceUrl) seenSources.add(next.sourceUrl);
    seenSlugs.add(next.slug);
    result.push(next);
  }

  return { articles: result, changed };
}

export async function listAllArticles(): Promise<Article[]> {
  const articles = await readJson<Article[] | null>(ARTICLES_FILE, null);
  if (!articles || articles.length === 0) {
    await writeJson(ARTICLES_FILE, SEED_ARTICLES);
    return SEED_ARTICLES;
  }
  const { articles: cleaned, changed } = dedupeArticles(articles);
  if (changed) {
    await writeJson(ARTICLES_FILE, cleaned);
  }
  return cleaned;
}

export async function listPublishedArticles(): Promise<Article[]> {
  const all = await listAllArticles();
  return all
    .filter((a) => (a.status ?? "published") === "published")
    .sort((a, b) => +new Date(b.publishedAt) - +new Date(a.publishedAt));
}

export async function getArticleById(id: string): Promise<Article | undefined> {
  const all = await listAllArticles();
  return all.find((a) => a.id === id);
}

export async function getArticleBySlug(
  slug: string,
): Promise<Article | undefined> {
  const all = await listPublishedArticles();
  return all.find((a) => a.slug === slug);
}

export async function saveAllArticles(articles: Article[]) {
  await writeJson(ARTICLES_FILE, articles);
}

export async function createArticle(input: ArticleInput): Promise<Article> {
  const all = await listAllArticles();
  const baseSlug = slugify(input.slug || input.title) || `story-${Date.now()}`;
  let slug = baseSlug;
  let n = 1;
  while (all.some((a) => a.slug === slug)) {
    slug = `${baseSlug}-${n++}`;
  }
  const article: Article = {
    ...input,
    id: input.id || `a_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    slug,
    publishedAt: input.publishedAt || new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: input.status ?? "published",
    tags: input.tags ?? [],
    content: input.content?.length ? input.content : [input.dek || input.title],
  };
  all.unshift(article);
  await saveAllArticles(all);
  return article;
}

export async function updateArticle(
  id: string,
  patch: Partial<Article>,
): Promise<Article | null> {
  const all = await listAllArticles();
  const idx = all.findIndex((a) => a.id === id);
  if (idx < 0) return null;
  const next: Article = {
    ...all[idx],
    ...patch,
    id: all[idx].id,
    updatedAt: new Date().toISOString(),
  };
  if (patch.title && !patch.slug) {
    // keep existing slug unless explicitly changed
  }
  if (patch.slug) {
    next.slug = slugify(patch.slug);
  }
  all[idx] = next;
  await saveAllArticles(all);
  return next;
}

export async function deleteArticle(id: string): Promise<boolean> {
  const all = await listAllArticles();
  const next = all.filter((a) => a.id !== id);
  if (next.length === all.length) return false;
  await saveAllArticles(next);
  return true;
}

export async function upsertAutoArticles(
  incoming: Article[],
): Promise<{ added: number; skipped: number }> {
  const all = await listAllArticles();
  const existingIds = new Set(all.map((a) => a.id));
  const existingSlugs = new Set(all.map((a) => a.slug));
  const existingSources = new Set(
    all.map((a) => a.sourceUrl).filter(Boolean) as string[],
  );
  let added = 0;
  let skipped = 0;
  for (const item of incoming) {
    if (
      existingIds.has(item.id) ||
      existingSlugs.has(item.slug) ||
      (item.sourceUrl && existingSources.has(item.sourceUrl))
    ) {
      skipped++;
      continue;
    }
    all.unshift(item);
    existingIds.add(item.id);
    existingSlugs.add(item.slug);
    if (item.sourceUrl) existingSources.add(item.sourceUrl);
    added++;
  }
  if (added > 0) {
    const { articles: cleaned } = dedupeArticles(all);
    await saveAllArticles(cleaned);
  }
  return { added, skipped };
}

export async function listSubscribers(): Promise<Subscriber[]> {
  return readJson<Subscriber[]>(SUBSCRIBERS_FILE, []);
}

export async function addSubscriber(email: string): Promise<Subscriber> {
  const list = await listSubscribers();
  const normalized = email.trim().toLowerCase();
  const existing = list.find((s) => s.email === normalized);
  if (existing) return existing;
  const sub: Subscriber = {
    email: normalized,
    subscribedAt: new Date().toISOString(),
  };
  list.push(sub);
  await writeJson(SUBSCRIBERS_FILE, list);
  return sub;
}
