export type RegionId =
  | "global"
  | "americas"
  | "europe"
  | "asia"
  | "africa"
  | "oceania"
  | "middle-east";

export type CategoryId =
  | "politics"
  | "technology"
  | "climate"
  | "business"
  | "culture"
  | "science"
  | "security";

export type HomepageLayout = "classic" | "tech" | "magazine" | "minimal";

export type AiProviderId = "gemini" | "claude" | "grok" | "anthropic";

export interface Region {
  id: RegionId;
  name: string;
  short: string;
  description: string;
  accent: string;
}

export interface Category {
  id: CategoryId;
  name: string;
  description: string;
}

export interface ArticleSeo {
  metaTitle?: string;
  metaDescription?: string;
  focusKeyword?: string;
  canonicalUrl?: string;
  ogImage?: string;
  noindex?: boolean;
  schemaType?: "NewsArticle" | "BlogPosting" | "Article";
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  dek: string;
  content: string[];
  category: CategoryId;
  region: RegionId;
  city: string;
  country: string;
  lat: number;
  lng: number;
  author: string;
  publishedAt: string;
  updatedAt?: string;
  image: string;
  imageAlt: string;
  featured?: boolean;
  breaking?: boolean;
  tags: string[];
  autoGenerated?: boolean;
  source?: string;
  sourceUrl?: string;
  status?: "draft" | "published";
  /** Per-article SEO overrides */
  seo?: ArticleSeo;
  /** AI generation metadata */
  aiGenerated?: boolean;
  aiProvider?: AiProviderId | string;
}

/** Live map node (WorldGridMap / Plotly hover). */
export interface GridPulse {
  id: string;
  lat: number;
  lng: number;
  intensity: number;
  /** Story title — primary hover / tooltip line. */
  label: string;
  /** Story route segment for pin click → `/story/[slug]`. */
  articleSlug?: string;
  /** Origin city for map hover chrome. */
  city?: string;
  /** Origin country for map hover chrome. */
  country?: string;
  /** True when the story is flagged breaking (pulse / pin emphasis). */
  breaking?: boolean;
}

export interface SiteSeoSettings {
  defaultMetaTitle: string;
  defaultMetaDescription: string;
  defaultOgImage: string;
  twitterHandle: string;
  googleSiteVerification: string;
  bingSiteVerification: string;
  organizationName: string;
  organizationLogo: string;
  robotsIndex: boolean;
}

export interface SiteSettings {
  homepageLayout: HomepageLayout;
  autoSyncEnabled: boolean;
  autoSyncIntervalMinutes: number;
  lastSyncAt: string | null;
  lastSyncResult: string | null;
  siteName: string;
  tagline: string;
  seo?: SiteSeoSettings;
  /** Preferred default AI for generation */
  defaultAiProvider?: AiProviderId;
}

export interface Subscriber {
  email: string;
  subscribedAt: string;
}

/** Stored separately from settings; never sent to public pages. */
export interface ApiSecrets {
  geminiApiKey?: string;
  claudeApiKey?: string;
  /** Alias for Claude — Anthropic API key */
  anthropicApiKey?: string;
  grokApiKey?: string;
  updatedAt?: string;
}

export type ArticleInput = Omit<Article, "id" | "slug" | "publishedAt"> & {
  id?: string;
  slug?: string;
  publishedAt?: string;
};

export interface SeoScoreItem {
  id: string;
  label: string;
  pass: boolean;
  weight: number;
  hint?: string;
}

export interface SeoScore {
  score: number;
  max: number;
  grade: "A" | "B" | "C" | "D" | "F";
  items: SeoScoreItem[];
}
