import { z } from "zod";

export const categoryIdSchema = z.enum([
  "politics",
  "technology",
  "climate",
  "business",
  "culture",
  "science",
  "security",
]);

export const regionIdSchema = z.enum([
  "global",
  "americas",
  "europe",
  "asia",
  "africa",
  "oceania",
  "middle-east",
]);

export const articleCreateSchema = z.object({
  title: z.string().trim().min(1).max(300),
  slug: z.string().trim().max(120).optional(),
  dek: z.string().trim().max(2000).optional(),
  content: z.union([z.array(z.string()), z.string()]).optional(),
  category: categoryIdSchema.optional(),
  region: regionIdSchema.optional(),
  city: z.string().trim().max(120).optional(),
  country: z.string().trim().max(120).optional(),
  lat: z.coerce.number().min(-90).max(90).optional(),
  lng: z.coerce.number().min(-180).max(180).optional(),
  author: z.string().trim().max(120).optional(),
  image: z.string().max(2000).optional(),
  imageAlt: z.string().trim().max(500).optional(),
  featured: z.boolean().optional(),
  breaking: z.boolean().optional(),
  tags: z.union([z.array(z.string()), z.string()]).optional(),
  status: z.enum(["draft", "published"]).optional(),
  source: z.string().max(200).optional(),
  sourceUrl: z.string().max(2000).optional(),
  publishedAt: z.string().optional(),
  aiGenerated: z.boolean().optional(),
  aiProvider: z.string().max(40).optional(),
  autoGenerated: z.boolean().optional(),
  seo: z
    .object({
      metaTitle: z.string().max(200).optional(),
      metaDescription: z.string().max(400).optional(),
      focusKeyword: z.string().max(120).optional(),
      canonicalUrl: z.string().max(2000).optional(),
      ogImage: z.string().max(2000).optional(),
      noindex: z.boolean().optional(),
      schemaType: z.enum(["NewsArticle", "BlogPosting", "Article"]).optional(),
    })
    .optional(),
});

export const loginSchema = z.object({
  password: z.string().min(1).max(500),
});

export const newsletterSchema = z.object({
  email: z.string().trim().email().max(254),
});

export const aiProviderIdSchema = z.enum([
  "gemini",
  "claude",
  "grok",
  "anthropic",
]);

export const homepageLayoutSchema = z.enum([
  "classic",
  "tech",
  "magazine",
  "minimal",
]);

export const keyFieldIdSchema = z.enum([
  "geminiApiKey",
  "claudeApiKey",
  "anthropicApiKey",
  "grokApiKey",
]);

/** Stored API keys: length-capped, no control chars; never echo full values in GET. */
const apiKeyValueSchema = z
  .string()
  .trim()
  .min(1)
  .max(1024)
  .refine((s) => !/[\u0000-\u0008\u000A-\u001F\u007F]/.test(s), {
    message: "API key contains invalid characters",
  });

export const keysPutSchema = z
  .object({
    geminiApiKey: apiKeyValueSchema.optional(),
    claudeApiKey: apiKeyValueSchema.optional(),
    anthropicApiKey: apiKeyValueSchema.optional(),
    grokApiKey: apiKeyValueSchema.optional(),
  })
  .strict();

export const keysDeleteSchema = z
  .object({
    field: keyFieldIdSchema.optional(),
    clear: keyFieldIdSchema.optional(),
  })
  .refine((d) => Boolean(d.field || d.clear), {
    message: "field (or clear) is required",
  });

export const settingsPutSchema = z
  .object({
    homepageLayout: homepageLayoutSchema.optional(),
    autoSyncEnabled: z.boolean().optional(),
    autoSyncIntervalMinutes: z.coerce.number().min(5).max(1440).optional(),
    siteName: z.string().trim().min(1).max(120).optional(),
    tagline: z.string().trim().max(300).optional(),
    defaultAiProvider: aiProviderIdSchema.optional(),
    seo: z
      .object({
        defaultMetaTitle: z.string().trim().max(200).optional(),
        defaultMetaDescription: z.string().trim().max(500).optional(),
        defaultOgImage: z.string().trim().max(2000).optional(),
        twitterHandle: z.string().trim().max(80).optional(),
        googleSiteVerification: z.string().trim().max(200).optional(),
        bingSiteVerification: z.string().trim().max(200).optional(),
        organizationName: z.string().trim().max(200).optional(),
        organizationLogo: z.string().trim().max(2000).optional(),
        robotsIndex: z.boolean().optional(),
      })
      .optional(),
  })
  // Forms may send lastSyncAt etc.; ignore unknown keys
  .strip();

export const seoOptimizeSchema = z.object({
  title: z.string().trim().min(1).max(300),
  dek: z.string().max(2000).optional(),
  content: z
    .union([
      z.array(z.string().max(20_000)).max(200),
      z.string().max(100_000),
    ])
    .optional(),
  tags: z
    .union([z.array(z.string().max(80)).max(50), z.string().max(2000)])
    .optional(),
  imageAlt: z.string().max(500).optional(),
  slug: z.string().max(120).optional(),
  focusKeyword: z.string().max(120).optional(),
  category: z.string().max(80).optional(),
});

export function parseTags(
  tags: string[] | string | undefined,
): string[] {
  if (!tags) return [];
  if (Array.isArray(tags)) return tags.map((t) => t.trim()).filter(Boolean);
  return tags
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);
}
