import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/auth";
import { deleteLocalUpload } from "@/lib/ai/generate-image";
import {
  sanitizeContentBlocks,
  sanitizeHttpUrl,
} from "@/lib/sanitize";
import { deleteArticle, getArticleById, updateArticle } from "@/lib/store";
import { articleCreateSchema, parseTags } from "@/lib/validation";
import type { CategoryId, RegionId } from "@/lib/types";

type Ctx = { params: Promise<{ id: string }> };

export async function GET(_req: Request, ctx: Ctx) {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const { id } = await ctx.params;
  const article = await getArticleById(id);
  if (!article) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  return NextResponse.json({ article });
}

export async function PUT(req: Request, ctx: Ctx) {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const { id } = await ctx.params;
  try {
    const raw = await req.json();
    const existing = await getArticleById(id);
    if (!existing) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    // Partial update: validate known fields when present
    const parsed = articleCreateSchema.partial().safeParse(raw);
    if (!parsed.success) {
      return NextResponse.json(
        {
          error: "Validation failed",
          details: parsed.error.flatten().fieldErrors,
        },
        { status: 400 },
      );
    }
    const body = { ...raw, ...parsed.data };

    const patch: Record<string, unknown> = {};

    if (body.title != null) patch.title = String(body.title).trim();
    if (body.dek != null) patch.dek = String(body.dek).trim();
    if (body.slug != null) patch.slug = String(body.slug).trim();
    if (body.city != null) patch.city = String(body.city).trim();
    if (body.country != null) patch.country = String(body.country).trim();
    if (body.author != null) patch.author = String(body.author).trim();
    if (body.imageAlt != null) patch.imageAlt = String(body.imageAlt).trim();
    if (body.source != null) patch.source = String(body.source);
    if (body.status === "draft" || body.status === "published") {
      patch.status = body.status;
    }
    if (body.featured != null) patch.featured = Boolean(body.featured);
    if (body.breaking != null) patch.breaking = Boolean(body.breaking);
    if (body.lat != null) patch.lat = Number(body.lat);
    if (body.lng != null) patch.lng = Number(body.lng);
    if (body.category) patch.category = body.category as CategoryId;
    if (body.region) patch.region = body.region as RegionId;
    if (body.aiProvider != null) patch.aiProvider = body.aiProvider;
    if (body.aiGenerated != null) patch.aiGenerated = Boolean(body.aiGenerated);
    if (body.autoGenerated != null) {
      patch.autoGenerated = Boolean(body.autoGenerated);
    }
    if (body.publishedAt != null) patch.publishedAt = body.publishedAt;

    if (typeof body.content === "string") {
      const { htmlToParagraphs } = await import("@/lib/editor-content");
      patch.content = sanitizeContentBlocks(
        body.content.includes("<")
          ? htmlToParagraphs(body.content)
          : body.content
              .split(/\n+/)
              .map((p: string) => p.trim())
              .filter(Boolean),
      );
    } else if (Array.isArray(body.content)) {
      patch.content = sanitizeContentBlocks(body.content);
    }

    if (body.tags != null) {
      patch.tags = parseTags(body.tags);
    }

    if (body.image != null && body.clearImage !== true) {
      const img = String(body.image);
      patch.image =
        sanitizeHttpUrl(img) ||
        (img.startsWith("/uploads/") ? img : existing.image);
    }

    if (body.sourceUrl != null) {
      const cleaned = sanitizeHttpUrl(body.sourceUrl);
      patch.sourceUrl = cleaned || undefined;
    }

    if (body.seo && typeof body.seo === "object") {
      const seo = body.seo as Record<string, unknown>;
      patch.seo = {
        ...(existing.seo || {}),
        ...seo,
        canonicalUrl:
          sanitizeHttpUrl(String(seo.canonicalUrl || "")) ||
          existing.seo?.canonicalUrl,
        ogImage:
          sanitizeHttpUrl(String(seo.ogImage || "")) ||
          (String(seo.ogImage || "").startsWith("/uploads/")
            ? String(seo.ogImage)
            : existing.seo?.ogImage),
      };
    }

    // Clear image + delete local upload
    if (body.clearImage === true) {
      if (existing.image?.startsWith("/uploads/")) {
        await deleteLocalUpload(existing.image);
      }
      patch.image = "";
      patch.imageAlt = "";
      if (existing.seo?.ogImage === existing.image) {
        patch.seo = {
          ...((patch.seo as object) || existing.seo || {}),
          ogImage: "",
        };
      }
    }

    const article = await updateArticle(id, patch);
    if (!article) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return NextResponse.json({ article });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Update failed" },
      { status: 500 },
    );
  }
}

export async function DELETE(_req: Request, ctx: Ctx) {
  if (!(await isAdminAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const { id } = await ctx.params;
  const existing = await getArticleById(id);
  if (existing?.image?.startsWith("/uploads/")) {
    await deleteLocalUpload(existing.image);
  }
  const ok = await deleteArticle(id);
  if (!ok) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  return NextResponse.json({ ok: true });
}
