import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdminAuthenticated } from "@/lib/auth";
import { listAllArticles } from "@/lib/store";
import { DeleteArticleButton } from "./DeleteArticleButton";

export const dynamic = "force-dynamic";

export default async function AdminArticlesPage() {
  if (!(await isAdminAuthenticated())) redirect("/admin/login");
  const articles = await listAllArticles();

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-3xl font-bold text-news-ink dark:text-white">
            Articles
          </h1>
          <p className="text-sm text-news-muted">
            {articles.length} total — add, edit, or remove manually.
          </p>
        </div>
        <Link
          href="/admin/articles/new"
          className="inline-flex h-10 items-center bg-news-red px-4 text-xs font-bold uppercase tracking-wide text-white"
        >
          + New article
        </Link>
      </div>

      <div className="overflow-x-auto border border-news-line bg-white shadow-sm dark:border-white/10 dark:bg-white/5">
        <table className="min-w-full text-left text-sm">
          <thead className="border-b border-news-line bg-news-soft text-xs uppercase tracking-wider text-news-muted dark:border-white/10 dark:bg-white/5">
            <tr>
              <th className="px-4 py-3">Title</th>
              <th className="px-4 py-3">Type</th>
              <th className="px-4 py-3">Category</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3">Published</th>
              <th className="px-4 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-news-line dark:divide-white/10">
            {articles.map((a) => (
              <tr key={a.id} className="align-top">
                <td className="max-w-xs px-4 py-3">
                  <Link
                    href={`/admin/articles/${a.id}`}
                    className="font-semibold text-news-ink hover:text-news-red dark:text-white"
                  >
                    {a.title}
                  </Link>
                  <p className="mt-0.5 text-xs text-news-muted">{a.slug}</p>
                </td>
                <td className="px-4 py-3 text-xs">
                  {a.autoGenerated ? (
                    <span className="bg-blue-50 px-2 py-0.5 font-semibold text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">
                      Auto
                    </span>
                  ) : (
                    <span className="bg-emerald-50 px-2 py-0.5 font-semibold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">
                      Manual
                    </span>
                  )}
                </td>
                <td className="px-4 py-3 capitalize text-news-muted">
                  {a.category}
                </td>
                <td className="px-4 py-3 capitalize text-news-muted">
                  {a.status || "published"}
                </td>
                <td className="px-4 py-3 text-xs text-news-muted">
                  {new Date(a.publishedAt).toLocaleString()}
                </td>
                <td className="px-4 py-3">
                  <div className="flex justify-end gap-2">
                    <Link
                      href={`/admin/articles/${a.id}`}
                      className="text-xs font-bold text-news-ink hover:text-news-red dark:text-white"
                    >
                      Edit
                    </Link>
                    <Link
                      href={`/story/${a.slug}`}
                      className="text-xs font-bold text-news-muted hover:text-news-red"
                    >
                      View
                    </Link>
                    <DeleteArticleButton id={a.id} title={a.title} />
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
