import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdminAuthenticated } from "@/lib/auth";
import { getSecretsStatus } from "@/lib/secrets";
import { listAllArticles, getSettings, listSubscribers } from "@/lib/store";
import { AdminActions } from "./AdminActions";

export const dynamic = "force-dynamic";

export default async function AdminDashboardPage() {
  if (!(await isAdminAuthenticated())) redirect("/admin/login");

  const [articles, settings, subscribers, keyStatus] = await Promise.all([
    listAllArticles(),
    getSettings(),
    listSubscribers(),
    getSecretsStatus(),
  ]);

  const published = articles.filter((a) => (a.status ?? "published") === "published");
  const auto = articles.filter((a) => a.autoGenerated);
  const drafts = articles.filter((a) => a.status === "draft");

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-news-ink dark:text-white">
            Dashboard
          </h1>
          <p className="mt-1 text-sm text-news-muted">
            Manage stories, auto-sync world news, and site layout.
          </p>
        </div>
        <AdminActions />
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        {[
          { label: "All articles", value: String(articles.length) },
          { label: "Published", value: String(published.length) },
          { label: "Auto-synced", value: String(auto.length) },
          { label: "Subscribers", value: String(subscribers.length) },
          {
            label: "Gemini (images)",
            value: keyStatus.geminiReady ? "Ready" : "Missing",
            warn: !keyStatus.geminiReady,
          },
        ].map((s) => (
          <div
            key={s.label}
            className="border border-news-line bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5"
          >
            <p className="text-xs font-bold uppercase tracking-wider text-news-muted">
              {s.label}
            </p>
            <p
              className={`mt-2 text-2xl font-black sm:text-3xl ${
                "warn" in s && s.warn
                  ? "text-news-red"
                  : "text-news-ink dark:text-white"
              }`}
            >
              {s.value}
            </p>
            {"warn" in s && s.warn && (
              <Link
                href="/admin/keys"
                className="mt-1 inline-block text-xs font-bold text-news-red hover:underline"
              >
                Add key →
              </Link>
            )}
          </div>
        ))}
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="border border-news-line bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5">
          <h2 className="font-bold text-news-ink dark:text-white">Auto sync</h2>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Status</dt>
              <dd className="font-semibold text-news-ink dark:text-white">
                {settings.autoSyncEnabled ? "Enabled" : "Disabled"}
              </dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Interval</dt>
              <dd className="font-semibold text-news-ink dark:text-white">
                {settings.autoSyncIntervalMinutes} min
              </dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Last sync</dt>
              <dd className="font-semibold text-news-ink dark:text-white">
                {settings.lastSyncAt
                  ? new Date(settings.lastSyncAt).toLocaleString()
                  : "Never"}
              </dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Result</dt>
              <dd className="text-right font-semibold text-news-ink dark:text-white">
                {settings.lastSyncResult || "—"}
              </dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Homepage layout</dt>
              <dd className="font-semibold capitalize text-news-ink dark:text-white">
                {settings.homepageLayout}
              </dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt className="text-news-muted">Drafts</dt>
              <dd className="font-semibold text-news-ink dark:text-white">
                {drafts.length}
              </dd>
            </div>
          </dl>
          <Link
            href="/admin/settings"
            className="mt-4 inline-block text-sm font-bold text-news-red hover:underline"
          >
            Edit settings →
          </Link>
        </div>

        <div className="border border-news-line bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5">
          <div className="flex items-center justify-between">
            <h2 className="font-bold text-news-ink dark:text-white">
              Recent articles
            </h2>
            <Link
              href="/admin/articles"
              className="text-sm font-bold text-news-red hover:underline"
            >
              View all
            </Link>
          </div>
          <ul className="mt-4 divide-y divide-news-line dark:divide-white/10">
            {articles.slice(0, 8).map((a) => (
              <li key={a.id} className="flex items-start justify-between gap-3 py-3">
                <div className="min-w-0">
                  <Link
                    href={`/admin/articles/${a.id}`}
                    className="line-clamp-1 text-sm font-semibold text-news-ink hover:text-news-red dark:text-white"
                  >
                    {a.title}
                  </Link>
                  <p className="mt-0.5 text-xs text-news-muted">
                    {a.autoGenerated ? "Auto" : "Manual"} · {a.category} ·{" "}
                    {a.status || "published"}
                  </p>
                </div>
                <Link
                  href={`/story/${a.slug}`}
                  className="shrink-0 text-xs text-news-muted hover:text-news-red"
                >
                  View
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="flex flex-wrap gap-3">
        <Link
          href="/admin/ai"
          className="inline-flex h-11 items-center bg-news-red px-5 text-sm font-bold uppercase tracking-wide text-white hover:bg-news-red-dark"
        >
          AI News Studio
        </Link>
        <Link
          href="/admin/articles/new"
          className="inline-flex h-11 items-center border border-news-line px-5 text-sm font-bold uppercase tracking-wide text-news-ink hover:border-news-red hover:text-news-red dark:border-white/15 dark:text-white"
        >
          Add article
        </Link>
        <Link
          href="/admin/articles"
          className="inline-flex h-11 items-center border border-news-line px-5 text-sm font-bold uppercase tracking-wide text-news-ink hover:border-news-red hover:text-news-red dark:border-white/15 dark:text-white"
        >
          Manage articles
        </Link>
        <Link
          href="/admin/seo"
          className="inline-flex h-11 items-center border border-news-line px-5 text-sm font-bold uppercase tracking-wide text-news-ink hover:border-news-red hover:text-news-red dark:border-white/15 dark:text-white"
        >
          SEO plugin
        </Link>
        <Link
          href="/admin/keys"
          className="inline-flex h-11 items-center border border-news-line px-5 text-sm font-bold uppercase tracking-wide text-news-ink hover:border-news-red hover:text-news-red dark:border-white/15 dark:text-white"
        >
          AI keys
        </Link>
      </div>
    </div>
  );
}
