import { ArticleCard } from "@/components/ArticleCard";
import { Badge } from "@/components/Badge";
import { ReadingProgress } from "@/components/ReadingProgress";
import { Sidebar } from "@/components/Sidebar";
import {
  categories,
  getArticleBySlug,
  getArticleMeta,
  getCategory,
  getLatestArticles,
  getRelatedArticles,
  getRegion,
} from "@/lib/articles";
import { contentBlocksToHtml } from "@/lib/editor-content";
import {
  buildNewsArticleJsonLd,
  resolveArticleMeta,
} from "@/lib/seo";
import { getSettings, listPublishedArticles } from "@/lib/store";
import { formatRelativeDate } from "@/lib/utils";
import { Clock, ExternalLink, MapPin, User } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

type Props = { params: Promise<{ slug: string }> };

export const dynamic = "force-dynamic";

export async function generateStaticParams() {
  const articles = await listPublishedArticles();
  return articles.slice(0, 50).map((a) => ({ slug: a.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const [article, settings] = await Promise.all([
    getArticleBySlug(slug),
    getSettings(),
  ]);
  if (!article) return { title: "Story not found" };
  const meta = resolveArticleMeta(article, settings.seo);
  return {
    title: meta.title,
    description: meta.description,
    alternates: { canonical: meta.canonical },
    robots: meta.noindex
      ? { index: false, follow: false }
      : { index: true, follow: true },
    openGraph: {
      title: meta.title,
      description: meta.description,
      type: "article",
      url: meta.canonical,
      publishedTime: article.publishedAt,
      modifiedTime: article.updatedAt || article.publishedAt,
      authors: [article.author],
      images: meta.image
        ? [{ url: meta.image, alt: article.imageAlt || meta.title }]
        : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.description,
      images: meta.image ? [meta.image] : undefined,
    },
    keywords: [
      article.seo?.focusKeyword,
      ...article.tags,
      article.category,
      article.region,
    ].filter(Boolean) as string[],
  };
}

export default async function StoryPage({ params }: Props) {
  const { slug } = await params;
  const article = await getArticleBySlug(slug);
  if (!article) notFound();

  const settings = await getSettings();
  const category = getCategory(article.category);
  const region = getRegion(article.region);
  const meta = getArticleMeta(article);
  const [related, latest] = await Promise.all([
    getRelatedArticles(article, 3),
    getLatestArticles(8),
  ]);
  const jsonLd = buildNewsArticleJsonLd(article, settings.seo);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <ReadingProgress />
      <div className="grid gap-8 lg:grid-cols-12">
        <article className="lg:col-span-8">
          <div className="mb-4 flex flex-wrap items-center gap-2 text-xs">
            <Link href="/" className="text-news-muted hover:text-news-red">
              Home
            </Link>
            <span className="text-news-line">/</span>
            <Link
              href={`/categories/${article.category}`}
              className="text-news-muted hover:text-news-red"
            >
              {category?.name}
            </Link>
          </div>

          <div className="flex flex-wrap gap-2">
            {article.breaking && <Badge>Breaking</Badge>}
            {/* RSS wire only — AI articles display as normal editorial posts */}
            {article.autoGenerated && !article.aiGenerated && (
              <Badge tone="dark">Live wire</Badge>
            )}
            <Badge>{category?.name}</Badge>
            <Link href={`/regions/${article.region}`}>
              <Badge tone="soft">{region?.name}</Badge>
            </Link>
          </div>

          <h1 className="mt-4 font-display text-3xl font-bold leading-tight text-news-ink text-balance dark:text-white sm:text-4xl lg:text-[2.75rem]">
            {article.title}
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-news-muted">
            {article.dek}
          </p>

          <div className="meta-row mt-6 border-y border-news-line py-4 text-sm dark:border-white/10">
            <span className="inline-flex items-center gap-1.5 font-semibold text-news-ink dark:text-white">
              <User className="h-4 w-4 text-news-red" />
              {article.author}
            </span>
            <span className="inline-flex items-center gap-1.5">
              <Clock className="h-4 w-4" />
              {formatRelativeDate(article.publishedAt)} · {meta.minutes} min
              read
            </span>
            <span className="inline-flex items-center gap-1.5">
              <MapPin className="h-4 w-4 text-news-red" />
              {article.city}, {article.country}
            </span>
          </div>

          <div className="relative mt-6 aspect-[16/9] overflow-hidden">
            <Image
              src={article.image}
              alt={article.imageAlt}
              fill
              className="object-cover"
              sizes="(max-width: 1024px) 100vw, 800px"
              priority
              unoptimized={article.autoGenerated}
            />
          </div>

          <div
            className="prose-news classic-content mt-8 dark:text-white/85"
            dangerouslySetInnerHTML={{
              __html: contentBlocksToHtml(article.content),
            }}
          />

          {article.sourceUrl && (
            <a
              href={article.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-news-red hover:underline"
            >
              Read original source
              <ExternalLink className="h-4 w-4" />
            </a>
          )}

          <div className="mt-8 flex flex-wrap gap-2 border-t border-news-line pt-6 dark:border-white/10">
            {article.tags.map((tag) => (
              <Link
                key={tag}
                href={`/search?q=${encodeURIComponent(tag)}`}
                className="border border-news-line px-2.5 py-1 text-xs font-semibold text-news-muted hover:border-news-red hover:text-news-red dark:border-white/15"
              >
                {tag}
              </Link>
            ))}
          </div>

          {related.length > 0 && (
            <section className="mt-12">
              <h2 className="section-title dark:text-white">Related posts</h2>
              <div className="grid gap-4 sm:grid-cols-3">
                {related.map((a) => (
                  <ArticleCard key={a.id} article={a} />
                ))}
              </div>
            </section>
          )}
        </article>

        <div className="lg:col-span-4">
          <div className="lg:sticky lg:top-16">
            <Sidebar
              trending={latest.slice(0, 5)}
              popular={latest.slice(1, 6)}
              categories={categories}
            />
          </div>
        </div>
      </div>
    </>
  );
}
