import Image from "next/image";
import Link from "next/link";
import { Clock, User } from "lucide-react";
import type { Article } from "@/lib/types";
import { categories } from "@/lib/constants";
import { cn, formatRelativeDate } from "@/lib/utils";
import { Badge } from "./Badge";

function getCategory(id: string) {
  return categories.find((c) => c.id === id);
}

function NewsImage({
  article,
  className,
  sizes,
  priority,
}: {
  article: Article;
  className?: string;
  sizes?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={article.image}
      alt={article.imageAlt}
      fill
      className={className}
      sizes={sizes}
      priority={priority}
      unoptimized={Boolean(article.autoGenerated)}
    />
  );
}

export function ArticleCard({
  article,
  variant = "default",
  rank,
}: {
  article: Article;
  variant?:
    | "default"
    | "featured"
    | "hero"
    | "overlay"
    | "list"
    | "compact"
    | "horizontal"
    | "trending";
  rank?: number;
}) {
  const category = getCategory(article.category);

  if (variant === "trending") {
    return (
      <Link
        href={`/story/${article.slug}`}
        className="group flex gap-3 border-b border-news-line py-3 last:border-0 dark:border-white/10"
      >
        <span className="flex h-8 w-8 shrink-0 items-center justify-center bg-news-soft text-sm font-black text-news-red dark:bg-white/10">
          {String(rank ?? 1).padStart(2, "0")}
        </span>
        <div className="min-w-0">
          <p className="line-clamp-2 text-sm font-bold leading-snug text-news-ink group-hover:text-news-red dark:text-white">
            {article.title}
          </p>
          <p className="mt-1 text-xs text-news-muted dark:text-white/60">
            {formatRelativeDate(article.publishedAt)}
          </p>
        </div>
      </Link>
    );
  }

  if (variant === "compact" || variant === "list") {
    return (
      <Link
        href={`/story/${article.slug}`}
        className="group flex gap-3 border-b border-news-line py-3 last:border-0 dark:border-white/10"
      >
        <div className="relative h-[72px] w-[96px] shrink-0 overflow-hidden bg-news-soft dark:bg-white/5">
          <NewsImage
            article={article}
            className="object-cover transition duration-500 group-hover:scale-105"
            sizes="96px"
          />
        </div>
        <div className="min-w-0">
          <span className="text-[10px] font-bold uppercase tracking-wider text-news-red">
            {category?.name}
          </span>
          <p className="mt-0.5 line-clamp-2 text-sm font-bold leading-snug text-news-ink group-hover:text-news-red dark:text-white">
            {article.title}
          </p>
          <p className="mt-1 text-xs text-news-muted dark:text-white/60">
            {formatRelativeDate(article.publishedAt)}
          </p>
        </div>
      </Link>
    );
  }

  if (variant === "horizontal") {
    return (
      <Link
        href={`/story/${article.slug}`}
        className="news-card group grid overflow-hidden sm:grid-cols-[240px_1fr]"
      >
        <div className="relative min-h-44 sm:min-h-full">
          <NewsImage
            article={article}
            className="object-cover transition duration-500 group-hover:scale-105"
            sizes="(max-width: 640px) 100vw, 240px"
          />
        </div>
        <div className="flex flex-col justify-center p-5">
          <Badge>{category?.name}</Badge>
          <h3 className="mt-2 text-xl font-bold leading-snug text-news-ink group-hover:text-news-red text-balance dark:text-white">
            {article.title}
          </h3>
          <p className="mt-2 line-clamp-2 text-sm text-news-muted dark:text-white/70">
            {article.dek}
          </p>
          <div className="meta-row mt-3 dark:text-white/55">
            <span className="inline-flex items-center gap-1">
              <User className="h-3 w-3" />
              {article.author}
            </span>
            <span className="inline-flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatRelativeDate(article.publishedAt)}
            </span>
          </div>
        </div>
      </Link>
    );
  }

  if (variant === "hero" || variant === "overlay") {
    return (
      <Link
        href={`/story/${article.slug}`}
        className={cn(
          "group relative block overflow-hidden",
          variant === "hero" ? "min-h-[380px] sm:min-h-[460px]" : "min-h-[220px]",
        )}
      >
        <NewsImage
          article={article}
          className="object-cover transition duration-700 group-hover:scale-105"
          sizes={variant === "hero" ? "(max-width: 1024px) 100vw, 66vw" : "33vw"}
          priority={variant === "hero"}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/35 to-transparent" />
        <div className="absolute inset-x-0 bottom-0 p-5 sm:p-7">
          <div className="flex flex-wrap gap-2">
            {article.breaking && <Badge tone="red">Breaking</Badge>}
            <Badge tone="dark">{category?.name}</Badge>
          </div>
          <h2
            className={cn(
              "mt-3 font-bold leading-tight text-white group-hover:text-news-red text-balance",
              variant === "hero"
                ? "text-2xl sm:text-3xl lg:text-4xl"
                : "text-lg sm:text-xl",
            )}
          >
            {article.title}
          </h2>
          {variant === "hero" && (
            <p className="mt-2 line-clamp-2 max-w-2xl text-sm text-white/80 sm:text-base">
              {article.dek}
            </p>
          )}
          <div className="meta-row mt-3 text-white/70">
            <span>{article.author}</span>
            <span>{formatRelativeDate(article.publishedAt)}</span>
            <span>
              {article.city}, {article.country}
            </span>
          </div>
        </div>
      </Link>
    );
  }

  if (variant === "featured") {
    return (
      <Link
        href={`/story/${article.slug}`}
        className="news-card group grid overflow-hidden lg:grid-cols-2"
      >
        <div className="relative min-h-56 lg:min-h-[280px]">
          <NewsImage
            article={article}
            className="object-cover transition duration-500 group-hover:scale-105"
            sizes="(max-width: 1024px) 100vw, 50vw"
          />
        </div>
        <div className="flex flex-col justify-center p-6">
          <Badge>{category?.name}</Badge>
          <h3 className="mt-3 text-2xl font-bold leading-snug text-news-ink group-hover:text-news-red text-balance dark:text-white">
            {article.title}
          </h3>
          <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-news-muted dark:text-white/70">
            {article.dek}
          </p>
          <div className="meta-row mt-4 dark:text-white/55">
            <span>{article.author}</span>
            <span>{formatRelativeDate(article.publishedAt)}</span>
          </div>
        </div>
      </Link>
    );
  }

  // default grid card
  return (
    <Link href={`/story/${article.slug}`} className="news-card group flex h-full flex-col">
      <div className="relative aspect-[16/10] overflow-hidden">
        <NewsImage
          article={article}
          className="object-cover transition duration-500 group-hover:scale-105"
          sizes="(max-width: 768px) 100vw, 33vw"
        />
        <div className="absolute left-3 top-3">
          <Badge>{category?.name}</Badge>
        </div>
      </div>
      <div className="flex flex-1 flex-col p-4">
        <h3 className="line-clamp-2 text-lg font-bold leading-snug text-news-ink group-hover:text-news-red dark:text-white">
          {article.title}
        </h3>
        <p className="mt-2 line-clamp-2 text-sm text-news-muted dark:text-white/70">
          {article.dek}
        </p>
        <div className="meta-row mt-auto pt-3 dark:text-white/55">
          <span className="inline-flex items-center gap-1">
            <User className="h-3 w-3" />
            {article.author}
          </span>
          <span>{formatRelativeDate(article.publishedAt)}</span>
        </div>
      </div>
    </Link>
  );
}
