import { redirect, notFound } from "next/navigation";
import { isAdminAuthenticated } from "@/lib/auth";
import { getArticleById } from "@/lib/store";
import { ArticleForm } from "../ArticleForm";

type Props = { params: Promise<{ id: string }> };

export const dynamic = "force-dynamic";

export default async function EditArticlePage({ params }: Props) {
  if (!(await isAdminAuthenticated())) redirect("/admin/login");
  const { id } = await params;
  const article = await getArticleById(id);
  if (!article) notFound();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-news-ink dark:text-white">
          Edit article
        </h1>
        <p className="text-sm text-news-muted">
          {article.autoGenerated ? "Auto-synced wire" : "Manual"} · {article.id}
        </p>
      </div>
      <ArticleForm mode="edit" initial={article} />
    </div>
  );
}
